#include"TxtStr_Order_DSX.h"
const char LangStr_German[] = {
"3. REIHE LINKS"CRLF
"3. REIHE RECHTS"CRLF
"AKTUELL"CRLF
"PO2/MOD"CRLF
"EINSTELLEN"CRLF
"LUFT"CRLF
"ALARM"CRLF
"ALARM NIEDRIGE BATT"CRLF
"ALARME"CRLF
"ANALYSIEREN"CRLF
"ANALYSER"CRLF
"ANALYSIERT"CRLF
"AR"CRLF
"AUF"CRLF
"AUFSTIEG ZU SCHNELL"CRLF
"TON"CRLF
"LAUT ALARM"CRLF
"AKUSTISCH/VIBRATION"CRLF
"AUTO"CRLF
"AUTO DIM"CRLF
"AUTO HOCH"CRLF
"AUTO NIEDRIG"CRLF
"DURC. VERBRAUCH"CRLF
"\xc3\x98""TIEFE"CRLF
"\xc3\x98""TIEFE"CRLF
"\xc3\x98""TG ZEIT"CRLF
"AVG.SAC"CRLF
"\xc3\x98""TEMP"CRLF
"BAILOUT GASVERBRAUCH"CRLF
"BAILOUT PLAN"CRLF
"BAILOUT PO2 LIMITS"CRLF
"BAR"CRLF
"BATT OK"CRLF
"BATT LOW"CRLF
"AUFLADEN"CRLF
"BATTERY TOO LOW"CRLF
"LEER"CRLF
"BLUETOOTH"CRLF
"BLUETOOTHNAME"CRLF
"BLUETOOTH"CRLF
"PAARUNG"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"HELLIGKEIT"CRLF
"WIRD BERECHNET"CRLF
"EICHEN"CRLF
"NOCHMAL EICHEN"CRLF
"KALIBRIERUNG BASIERT AUF"CRLF
"KANN NICHT UNTER"CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"CC-6 DRUCK"CRLF
"CC-DRUCK"CRLF
"CDT"CRLF
"OBERGRENZE"CRLF
"SENSORSPANNUNG"CRLF
"ZIELORT \xc3\x84""NDERN"CRLF
"AKKU"CRLF
"CHRONO"CRLF
"GEWEBE ZUR\xc3\x9c""CKSETZEN"CRLF
"KOMMUNIKATION"CRLF
"KOMPASS"CRLF
"KOMPASS MENU"CRLF
"BEST\xc3\x84""TIGEN?"CRLF
"VERBINDEN"CRLF
"VERBUNDEN"CRLF
"VERBUNDEN - BLUETOOTH"CRLF
"VERBUNDEN"CRLF
"KONSERVATIV"CRLF
"KONSERVATIV - SPORT"CRLF
"KONSERVATIV - TEC"CRLF
"VERBRAUCH"CRLF
"FORTGESETZT"CRLF
"COUNTDOWN"CRLF
"AKTUELLER STANDORT"CRLF
"AKTUELLER PO2"CRLF
"AKTUELLER DRUCK"CRLF
"PERSON. SP"CRLF
"CYAN"CRLF
"T/M/J"CRLF
"DATEN"CRLF
"DATEN 1"CRLF
"DATEN 2"CRLF
"DATEN 3"CRLF
"DATUM"CRLF
"DAT FORM"CRLF
"DATUM & ZEIT"CRLF
"COMP"CRLF
"COMP INFO"CRLF
"OST"CRLF
"E"CRLF
"NORTH"CRLF
"N"CRLF
"SOUTH"CRLF
"S"CRLF
"WEST"CRLF
"W"CRLF
"DEKO"CRLF
"DEKO"CRLF
"DEKO EINTRAG"CRLF
"DECO PO2"CRLF
"DEKOSTOPP"CRLF
"- VERRINGERN"CRLF
"TIEFSTOPP"CRLF
"ORT L\xc3\x96""SCHEN?"CRLF
"BILD"CRLF
"WIRD GEL\xc3\x96""SCHT."CRLF
"FORTFAHREN?"CRLF
"WURDE GEL\xc3\x96""SCHT."CRLF
"TIEFE"CRLF
"TIEFE"CRLF
"TIEFEN ALARM"CRLF
"TIEFEN ALARM"CRLF
"AEQUIVALENTE NARKOTISCHE TIEFE(END)"CRLF
"HYPOXISCHER GRENZBEREICH(HT)"CRLF
"MAX OPERATIONSTIEFE(MOD)"CRLF
"ATMUNGSANSTRAENGUNG(WOB)"CRLF
"TIEFENGRENZE"CRLF
"DESAT"CRLF
"GERAETEEINSTELLUNGEN"CRLF
"VERD. PO2"CRLF
"DIMMHELLIGKEIT"CRLF
"BILDSCHIRM"CRLF
"BILDSCHRIM EINSTELLUNGEN"CRLF
"ENTFERNUNG"CRLF
"TAUCHGANG DATA"CRLF
"TAUCHGANG MEN\xc3\x9c"""CRLF
"TAUCHMODUS"CRLF
"TAUCHPLAN"CRLF
"TAUCH PLANER"CRLF
"TAUCHGANGSPROFILGRAPH"CRLF
"TG EINSTELLUNGEN"CRLF
"DEKOZEIT"CRLF
"> 99 MIN"CRLF
"TAUCHSIMULATOR"CRLF
"TAUCHZEIT"CRLF
"TAUCHZEITALARM"CRLF
"TAUCHZEIT/TTS"CRLF
"TAUCHZEIT/TTS ALARME"CRLF
"TAUCHGANGE"CRLF
"MAXIMALES LIMIT "CRLF
"\xc3\x9c""BERSCHREITET 400 FT"CRLF
"\xc3\x9c""BERSCHREITET 120M"CRLF
"NICHT GENUG ZEIT F\xc3\x9c""R "CRLF
"ABSTIEG"CRLF
"T.M"CRLF
"WECHSELN SIE"CRLF
"- LISTE UNTEN"CRLF
"STOP N UNTEN"CRLF
"DS VORSCHAU"CRLF
"DSX INFO"CRLF
"WIRD HERUNTERGELADEN"CRLF
"DTR"CRLF
"DTR ALARM"CRLF
"MARK ANWEND"CRLF
"MARK"CRLF
"ANWEND"CRLF
"H\xc3\x96""HENL"CRLF
"EN13319"CRLF
"ENDE"CRLF
"END ALARM"CRLF
"END DRUCK"CRLF
"END DRUCK AL"CRLF
"END DRUCK"CRLF
"END/WOB/ICD"CRLF
"END/WOB/ICD ALARME"CRLF
"EINTRAG"CRLF
"AEQUIVALENTE NARKOTISCHE TIEFE"CRLF
"ERROR"CRLF
"FEHLER"CRLF
"ALTITUDE"CRLF
"FEHLER"CRLF
"A BIS D"CRLF
"FEHLER"CRLF
"EICHUNG"CRLF
"PR\xc3\x9c""FSUMMEN"CRLF
"FEHLER"CRLF
"FEHLER"CRLF
"EEPROM"CRLF
"FEHLER"CRLF
"LETZTER"CRLF
"TAUCHGANG"CRLF
"WAYFINDER VERLASSEN"CRLF
"EXIT TIME"CRLF
"EXTRA GROB"CRLF
"GESCHEITERT"CRLF
"SCHN."CRLF
"FHE KANN NICHT ZU 0 "CRLF
"GEAENDERT WERDEN "CRLF
"WAEHREND FO2 < 21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"BILDSCHIRM DREHEN"CRLF
"FLIEGEN"CRLF
"FO2"CRLF
"S\xc3\x9c""WASS"CRLF
"GAS"CRLF
"GAS 1"CRLF
"GAS 2"CRLF
"GAS 3"CRLF
"GAS 4"CRLF
"GASVERBRAUCHE"CRLF
"GAS WECHSELN"CRLF
"GAS ZEIT"CRLF
"VERBLEIBENDE GASZEIT 5 MIN"CRLF
"TIEFMESS"CRLF
"GAUGE SM"CRLF
"GF"CRLF
"HOHER GF"CRLF
"GF(H\xc3\x96""CHSTER)"CRLF
"NIEDRIGER GF"CRLF
"GF/N2"CRLF
"AUSGEWAEHLTER GF"CRLF
"GFBG"CRLF
"GFBG ODER TLBG"CRLF
"ORT AUFSUCHEN?"CRLF
"AUFST"CRLF
"GPS"CRLF
"ORT L\xc3\x96""SCHEN"CRLF
"GPS MEN\xc3\x9c"""CRLF
"SIE M\xc3\x9c""SSEN EINEN ORT "CRLF
"L\xc3\x96""SCHEN, UM EINEN NEUEN "CRLF
"ZU SPEICHERN"CRLF
"KEIN GPS SIGNAL"CRLF
"GEFUNDEN"CRLF
"WARTE AUF"CRLF
"GPS SIGNAL"CRLF
"GR\xc3\x9c""N"CRLF
"GTR"CRLF
"GTR F\xc3\x9c""R L & R"CRLF
"HOCH"CRLF
"ZU HOHER PO2"CRLF
"HOHER SP"CRLF
"HISTORIE"CRLF
"\xc3\x98""TIEFE"CRLF
"NIEDRIGSTE TEMPERATUR"CRLF
"MAX TIEFE"CRLF
"MAX TAUCHZEIT"CRLF
"MAX H\xc3\x96""HENLAGE"CRLF
"GESAMTE TAUCHZEIT"CRLF
"HAUPTMEN\xc3\x9c"""CRLF
"HAUPTMEN\xc3\x9c"""CRLF
"STD"CRLF
"ST:MIN"CRLF
"ICD"CRLF
"ICD ALARME"CRLF
"WENN ER MIT "CRLF
"IMPERIAL"CRLF
"- ERH\xc3\x96""HEN"CRLF
"INFO"CRLF
"EINLEITEN"CRLF
"GPS LADEN"CRLF
" IST VERBUNDEN MIT "CRLF
"EINSTELLUNG IST"CRLF
"ISOBARISCHE ZAEHLERDIFFUSION"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"SPRACHE"CRLF
"LETZTE KALI"CRLF
"LETZTER TG"CRLF
"LETZTE TG DATEN"CRLF
"LETZTE GAS"CRLF
"LETZTE STOPPTIEFE"CRLF
"LIMIT"CRLF
"VERBUNDEN"CRLF
"VERBUNDEN TMT"CRLF
"ORT GEL\xc3\x96""SCHT"CRLF
"ORT GESPEICHERT"CRLF
"LOG"CRLF
"VERBFEHLER"CRLF
"TMT VERLOREN"CRLF
"NIED-"CRLF
"NIEDRIGE BATT"CRLF
"NIEDRIGER PO2"CRLF
"NIEDRIGER SP"CRLF
"MIN TEMP"CRLF
"M.T"CRLF
"M.T.J"CRLF
"MAGENTA"CRLF
"HAUPTBILDSCHIRM"CRLF
"HAUPTMEN\xc3\x9c"""CRLF
"HERSTELLER"CRLF
"MAX"CRLF
"MAX TIEFE"CRLF
"MAX TIEFE"CRLF
"MAX"CRLF
"TIEFE"CRLF
"MAX TAUCHZEIT"CRLF
"MAX H\xc3\x96""HENLAGE"CRLF
"MAX PO2"CRLF
"MITTEL"CRLF
"METRISCH"CRLF
"MIN"CRLF
"MIN:SEK"CRLF
"VERPASSTER DEKO"CRLF
"MOD"CRLF
"MODUS"CRLF
"MODELL"CRLF
"WEITERE DATEN"CRLF
"ANDERE TG DATEN"CRLF
"MEINE INFO"CRLF
"BILDDATEIEN MIT "CRLF
"DIVERLOG+ APP "CRLF
"HOCHLADEN"CRLF
" "CRLF
"N2"CRLF
"N2 BAR"CRLF
"N2 BAR ALARM"CRLF
"NEU"CRLF
"NEU ODER FORTGESETZT"CRLF
"WEITER"CRLF
"STICKSTOFF"CRLF
"KEIN"CRLF
"KEIN DEKO"CRLF
"KEIN DEKO ZEIT"CRLF
"NOCH KEIN TG"CRLF
"KEIN O2 SENSOR GEFUNDEN"CRLF
"BITTE MIT O2 SENSOR"CRLF
"VERBINDEN"CRLF
"KEIN BILD"CRLF
"KEIN TMT"CRLF
"NOCH KEIN"CRLF
"TAUCHGANG"CRLF
" "CRLF
"IST NICHT VERF\xc3\x9c""GBAR"CRLF
"NICHT VERF"CRLF
"O2 ANALYSER"CRLF
"O2 NARKOTISCH"CRLF
"O2 SAT"CRLF
"O2 SAT (ENDE)"CRLF
"O2 ZEIT"CRLF
"ANALYSIERTES GAS EINER"CRLF
"LISTE HINZUF\xc3\x9c""GEN?"CRLF
"KEIN O2 SENSOR GEFUNDEN"CRLF
"BITTE MIT O2 SENSOR"CRLF
"VERBINDEN"CRLF
"LUFTDRUCK"CRLF
"BEREIT ZU "CRLF
"KALIBRIEREN"CRLF
"OC-L ET OC-R"CRLF
"SERONT R\xc3\x89""GL\xc3\x89""S \xc3\x80"""CRLF
"25/45"CRLF
"PROC\xc3\x89""DER?"CRLF
"LISTE F\xc3\x9c""R"CRLF
"AUSW\xc3\x84""HLEN"CRLF
"KALIBRIERUNG"CRLF
"DES O2 SENSORS"CRLF
"ABGESCHLOSSEN"CRLF
"VOR DER ANALYSE"CRLF
"BITTE O2 SENSOR"CRLF
"KALIBRIEREN"CRLF
"ERMITTLE SPANNUNG O2 "CRLF
"SENSOR"CRLF
" "CRLF
"OC"CRLF
"OC-1"CRLF
"OC-2"CRLF
"OC-3"CRLF
"OC-4"CRLF
"OC-5"CRLF
"OC-6"CRLF
"OC DEKO PO2"CRLF
"OC-L"CRLF
"OC MAX. PO2"CRLF
"OC MIN. PO2"CRLF
"OC-R"CRLF
"AUS"CRLF
"AN"CRLF
"ORANGE"CRLF
"PAARUNG"CRLF
"PASSWORT"CRLF
"EICHUNG BESTANDEN"CRLF
"PERS\xc3\x96""NLICHE"CRLF
"PLAN"CRLF
"PO2"CRLF
"PO2 AL"CRLF
"PO2 < 0.17  ANN NICHT "CRLF
"GEWECHSELT WERDEN"CRLF
"PO2(H\xc3\x96""CHSTER)"CRLF
"PO2 GRENZEN"CRLF
"DRUCK"CRLF
"AKTIVIERUNGSDRUCK"CRLF
"DRUCK"CRLF
"BEREIT"CRLF
"REFERENZ"CRLF
"DURCHSCHNITTLICHE TIEFE ZUR\xc3\x9c""CKSETZEN"CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"SETTINGS WILL"CRLF
"BE RESET TO DEFAULTS"CRLF
"(TAUCHDATEN BLEIBEN ERHALTEN)"CRLF
"SIND SIE SICHER?"CRLF
"EINST. ZUR\xc3\x9c""CKSETZEN"CRLF
"ERGEBNIS"CRLF
"DREHEN UND WENDEN IN"CRLF
"VERSCHIEDENE RITUNGEN"CRLF
"BIS ES PIEPT"CRLF
"RTI AL"CRLF
"RTI ALARM"CRLF
"LAUFZEIT"CRLF
"LVO"CRLF
"SICHERHEITSSTOPP"CRLF
"SALZ"CRLF
"SALT WATER"CRLF
"AUFZRATE"CRLF
"- SPEICHERN"CRLF
"AKTUELLEN STANDORT SPEICHERN"CRLF
"ORT SPEICHERN?"CRLF
"PROFILE IST GESPEICHERT"CRLF
"MEER"CRLF
"SEARCH"CRLF
"SUCHE"CRLF
"TMT  WIRD GESUCHT"CRLF
"SEK"CRLF
"ABSCHNITTE"CRLF
"GAS F\xc3\x9c""R LISTE AUSW\xc3\x84""HLEN"CRLF
"SERIENNR."CRLF
"EINS."CRLF
"ALARM EINST"CRLF
"SET BO GAS"CRLF
"FO2 KALIBRIERGAS"CRLF
"EINSTELLEN"CRLF
"ABW. EINST."CRLF
"GAS EINSTELLEN"CRLF
"GF EINSTELLEN"CRLF
"HOHEN GF EINSTELLEN"CRLF
"EINSTELLUNGEN"CRLF
"SP EINSTELLEN"CRLF
"DIV EINST"CRLF
"EINSTELLUNG"CRLF
"EINSTELLUNGEN SIND "CRLF
"ZUR\xc3\x9c""CKGESETZT"CRLF
"EINSTELLUNGEN"CRLF
"EINSTELLUNG"CRLF
"TAUCHGANG SIMULIEREN"CRLF
"BILDER"CRLF
"LANGS."CRLF
"SM"CRLF
"SN:"CRLF
"SP"CRLF
"SP(HOCH-TIEF)"CRLF
"SP WECHSELN"CRLF
"SPORT"CRLF
"STANDARD"CRLF
"ANFANG"CRLF
"ANFANG ZEIT"CRLF
"STOPP"CRLF
"STOPP"CRLF
"\xc3\x9c""BERBLICK"CRLF
"OBERFL ZEIT"CRLF
"OBERFL ZEIT"CRLF
"WECHSEL BO\xcb\x83""CC"CRLF
"WECHSEL CC\xcb\x83""BO"CRLF
"GASWECHSEL DRUCK"CRLF
"WECHSEL ZU"CRLF
"WECHSELN ZUM PERS."CRLF
"WECHSELN ZU FO2"CRLF
"WECHSELN ZUM HOHEN"CRLF
"WECHSELN ZUM NIEDRIGEN"CRLF
"SYSTEM ERROR"CRLF
"FLASCHENDRUCK"CRLF
"FLASCHENDRUCK"CRLF
"ZIEL"CRLF
"ZIELORT"CRLF
"TEC"CRLF
"TEMP"CRLF
"DAS AKTUELLE GAS"CRLF
"DANN AKTIVIEREN SIE"CRLF
"ZEIT"CRLF
"ZEITFORM"CRLF
"ZEITLIMIT"CRLF
"GESAMTAUFSTIEGSDAUER ALARM"CRLF
"DIMMBEGINN"CRLF
"GEWEBES\xc3\x84""TTIGUNG"CRLF
"GEWEBE"CRLF
"TITELFARBE"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT L"CRLF
"BATT SEND NIED"CRLF
"TMT IST NICHT VERF\xc3\x9c""GBAR"CRLF
"TMT 6"CRLF
"SERIENNUMMER"CRLF
"SERIENNUMMER  EINSTELLEN"CRLF
"TMT STATUS"CRLF
"TMT WECHSEL"CRLF
"ZU"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- WECHSELN"CRLF
"- UMSCHALTEN"CRLF
"ZU TIEF"CRLF
"ZU SCHNELL"CRLF
"GESAMTE DEKO"CRLF
"GESAMTE TAUCHGANGE"CRLF
"GESAMTE TAUCHZEIT"CRLF
"GESAMTE LAUFZEIT"CRLF
"SENDER"CRLF
"TTS"CRLF
"UMK/END/WEC DRUCK"CRLF
"UMKDRUCK"CRLF
"UMKEHRDRUCK AL"CRLF
"UMK DRUCK"CRLF
"UMK/ENDDRUCK"CRLF
"UMK/ENDDRUCK ALARME"CRLF
"TYP"CRLF
"WASSER EINGESTELLT "CRLF
"WERDEN"CRLF
"EINHEITEN"CRLF
"- LISTE AUFWART"CRLF
"HOCHGL 1"CRLF
"HOCHGL 2"CRLF
"HOCHGL 3"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"EINST OPTIONEN"CRLF
"WERT"CRLF
"VIBRATION"CRLF
"VERSTOB"CRLF
"WARTEN SIE F\xc3\x9c""R DAS PIEPTON, "CRLF
"WARNUNG"CRLF
"WARNUNG! HYPOXISCHES GAS"CRLF
"WARNUNG NIEDRIGE BATT"CRLF
"WARNUNG! PO2 >1.60"CRLF
"WASSERTYP"CRLF
"WAYFINDER"CRLF
"STARTBILDSCHIRM "CRLF
"WEIB"CRLF
"VERBUNDEN WIRD, WIRD ER ZU KEINEM"CRLF
"WOB"CRLF
"WOB ALARM"CRLF
"ATMUNGSANSTRAENGUNG"CRLF
"JA"CRLF
"SIE SIND AM ZIEL ANGEKOMMEN"CRLF
};