#include"TxtStr_Order_DSX.h"
const char LangStr_Portugese[] = {
"3raLINHA ESQ"CRLF
"3ra LINHA DTA"CRLF
"ATUAL"CRLF
"PO2/MOD"CRLF
"AJUSTE"CRLF
"AR"CRLF
"ALARME"CRLF
"ALARME BATERIA FRACA"CRLF
"ALARMES"CRLF
"ANALISAR"CRLF
"ANALISADOR"CRLF
"A ANALISAR"CRLF
"VS"CRLF
"ASC"CRLF
"SUBIDA MUITO R\xc3\x81""PIDA"CRLF
"SONORO"CRLF
"ALARME SONORO"CRLF
"SONORO/VIBRA\xc3\x87\xc3\x83""O"CRLF
"AUTO"CRLF
"CONTRASTE AUTO"CRLF
"AUTO-ALTO"CRLF
"AUTO-BAIXO"CRLF
"M\xc3\x89""DIA CONSUMO"CRLF
"PROF MED"CRLF
"PROF MED"CRLF
"TEMPO M\xc3\x89""DIO"CRLF
"AVG.SAC"CRLF
"TEMP MED"CRLF
"CONSUMO GAS BAILOUT"CRLF
"PLANEAMENTO DE BAILOUT"CRLF
"LIMITES PO2 BAILOUT"CRLF
"BAR"CRLF
"BAT. BOA"CRLF
"BATERIA FRACA"CRLF
"BATERIA"CRLF
"BATTERY TOO LOW"CRLF
"VAZIO"CRLF
"BLUETOOTH"CRLF
"BT NOME EQUIPAMENTO"CRLF
"EMPARELHAR"CRLF
"BLUETOOTH"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"BRILHO"CRLF
"A CALCULAR"CRLF
"CALIBRAR"CRLF
"CALIBRAR NOVAMENTE"CRLF
"CALIBRA\xc3\x87\xc3\x83""O BASEADA EM"CRLF
"N\xc3\x83""O PODE SER DEFINIDO"CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"PRESS\xc3\x83""O CC-6"CRLF
"CC- PRESS\xc3\x83""O"CRLF
"CDT"CRLF
"TECTO"CRLF
"VOLTAGEM DA C\xc3\x89""LULA"CRLF
"MUDAR LOCALIZA\xc3\x87\xc3\x83""O DESTINO"CRLF
"CHARGE"CRLF
"CRONO"CRLF
"ZERAR TECIDOS"CRLF
"COMMUNICATION"CRLF
"B\xc3\x9a""SSOLA"CRLF
"MENU B\xc3\x9a""SSOLA"CRLF
"CONFIRMA?"CRLF
"LIGAR"CRLF
"LIGADO"CRLF
"LIGADO - BLUETOOTH"CRLF
"LIGA\xc3\x87\xc3\x83""O"CRLF
"FATOR CONSERVADOR"CRLF
"FATOR CONSERVADOR - DESPORTIVO"CRLF
"FATOR CONSERVADOR- TEC"CRLF
"CONSUMO"CRLF
"CONT."CRLF
"CONTAGEM REGRESSIVA"CRLF
"LOCALIZA\xc3\x87\xc3\x83""O ATUAL"CRLF
"PO2 ATUAL"CRLF
"P ATM ATUAL"CRLF
"SP PERSONAL."CRLF
"AZUL"CRLF
"D/M/A"CRLF
"DADOS"CRLF
"DADOS 1"CRLF
"DADOS 2"CRLF
"DADOS 3"CRLF
"DATA"CRLF
"FORMATO DATA"CRLF
"DATA E HORA"CRLF
"COMPUTADOR"CRLF
"INFO COMP"CRLF
"ESTE"CRLF
"E"CRLF
"NORTE"CRLF
"N"CRLF
"SUL"CRLF
"S"CRLF
"OESTE"CRLF
"O"CRLF
"DESCOMPRESS\xc3\x83""O"CRLF
"DESCO"CRLF
"ENTRADA DECO"CRLF
"DECO PO2"CRLF
"PATAMAR. DECO"CRLF
"- DIMINUIR"CRLF
"P-PROF"CRLF
"APAGAR LOCALIZA\xc3\x87\xc3\x83""O?"CRLF
"FICHA"CRLF
"SER\xc3\x81 APAGADA."CRLF
"DE CERTEZA?"CRLF
"APAGADA."CRLF
"PROF"CRLF
"PROF."CRLF
"AL PROF"CRLF
"ALARM PROF"CRLF
"PROFUNDI. NARC\xc3\x93""TICA EQUIVALENTE (END)"CRLF
"LIMIAR HIP\xc3\x93""XICO(HT)"CRLF
"PROFUNDI.M\xc3\x81""X. OPERACIONAL (MOD)"CRLF
"TRABALHO VENTILAT\xc3\x93""RIO(WOB)"CRLF
"PROFUNDIDADE LIMITE"CRLF
"DESAT"CRLF
"DEFINI\xc3\x87\xc3\x95""ES DISPOSITIVO"CRLF
"Dil PO2"CRLF
"REGULAR BRILHO P/"CRLF
"ECR\xc3\x83"""CRLF
"DEFINI\xc3\x87\xc3\x95""ES ECRA"CRLF
"DIST\xc3\x82""NCIA"CRLF
"DADOS MERGULHO"CRLF
"MENU MERGULHO"CRLF
"MODO MERGULHO"CRLF
"PLANEAMENTO MERGULHO"CRLF
"PLANEAMENTO MERGULHO"CRLF
"GR\xc3\x81""FICO PERFIL MERGULHO"CRLF
"DEFINI\xc3\x87\xc3\x95""ES MERGULHO"CRLF
"TEMPO DECO"CRLF
"> 99 MIN"CRLF
"SIMULADOR MERGULHO"CRLF
"TM"CRLF
"ALARME TEMPO MERGULHO"CRLF
"TM/TTS"CRLF
"ALARMES TM/TTS"CRLF
"MERGULHOS"CRLF
"TECTO M\xc3\x81""XIMO"CRLF
"EXCEDE 400 FT"CRLF
"EXCEDE 120 M"CRLF
"TEMPO INSUFICIENTE"CRLF
"PARA DESCIDA"CRLF
"DIA.M\xc3\x8a""S"CRLF
"N\xc3\x83""O TROCAR"CRLF
"- PARA BAIXO"CRLF
"PARA PATAMAR"CRLF
"PR\xc3\x89""-V DS"CRLF
"INFO DISPOSITIVO"CRLF
"TRM"CRLF
"AL TRM"CRLF
"MARCADOR APLICADO"CRLF
"MARCADOR"CRLF
"APLICADO"CRLF
"ALT"CRLF
"EN13319"CRLF
"END"CRLF
"PARAR ALARME"CRLF
"PRESS\xc3\x83""O FINAL"CRLF
"AL PRESS FINAL"CRLF
"PRESS\xc3\x83""O FINAL"CRLF
"END/WOB/ICB"CRLF
"ALARMES END/WOB/ICD"CRLF
"ENTRADA"CRLF
"PROF NARC\xc3\x93""TICA EQUIVAL."CRLF
"ERROR"CRLF
"ERRO"CRLF
"ALTITUDE"CRLF
"ERRO"CRLF
"A - D"CRLF
"ERRO DE"CRLF
"CALIBRA\xc3\x87\xc3\x83""O"CRLF
"ERRO"CRLF
"CHECKSUM"CRLF
"ERRO"CRLF
"EEPROM"CRLF
"EEPROM"CRLF
"\xc3\x9a""LTIMO MERGULHO"CRLF
" "CRLF
"SAIR DA BUSCA DE DIRE\xc3\x87\xc3\x95""ES"CRLF
"HORA DE SA\xc3\x8d""DA"CRLF
"GRANDE"CRLF
"FALHA"CRLF
"R\xc3\x81""PI."CRLF
"FiHe N\xc3\x83""O PODE SER"CRLF
"DEFINIDA PARA 0"CRLF
"SE FiO2 <21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"ROTA\xc3\x87\xc3\x83""O ECR\xc3\x83"""CRLF
"TEMP. PARA VO."CRLF
"FO2"CRLF
"DOCE"CRLF
"GASES"CRLF
"GAS 1"CRLF
"GAS 2"CRLF
"GAS 3"CRLF
"GAS 4"CRLF
"CONSUMO DE GAS"CRLF
"TROCA DE G\xc3\x81""S"CRLF
"TEMPO DE G\xc3\x81""S"CRLF
"TEMPO RESTANTE G\xc3\x81""S 5 MIN"CRLF
"GAUGE"CRLF
"GAUGE SM"CRLF
"GF"CRLF
"GF BAIXO"CRLF
"GF (MAIS ELEVADO)"CRLF
"GF ALTO"CRLF
"GF/N2"CRLF
"GF SELECIONADO"CRLF
"GFBG"CRLF
"GR\xc3\x81""F GF/N2"CRLF
"IR PARA LOCALIZA\xc3\x87\xc3\x83""O?"CRLF
"SUBA"CRLF
"GPS"CRLF
"APAGAR LOCALIZA\xc3\x87\xc3\x83""O"CRLF
"MENU GPS"CRLF
"DEVE APAGAR UMA"CRLF
"LOCALIZA\xc3\x87\xc3\x83""O PARA GRAVAR"CRLF
"UMA NOVA"CRLF
"SINAL DE GPS"CRLF
"N\xc3\x83""O ENCONTRADO"CRLF
"\xc3\x80 ESPERA DE"CRLF
"SINAL DE GPS"CRLF
"VERDE"CRLF
"GTR"CRLF
"TRG ESQ E DTO"CRLF
"ALTO"CRLF
"PO2 ALTA"CRLF
"SP ALTO"CRLF
"HIST\xc3\x93""RICO"CRLF
"PROF. M\xc3\x89""DIA"CRLF
"TEMP. MINIMA"CRLF
"PROFUNDIDADE M\xc3\x81""XIMA"CRLF
"TEMPO MAX. MERGULHO"CRLF
"MAX ALT"CRLF
"TEMPO TOTAL IMERS\xc3\x95""ES"CRLF
"MENU INICIAL"CRLF
"MENU INICIAL"CRLF
"HR"CRLF
"HR:MIN"CRLF
"ICD"CRLF
"ALARMES ICD"CRLF
"SE CONECTAR A"CRLF
"IMPERIAL"CRLF
"- AUMENTAR"CRLF
"INFO"CRLF
"INICIAR"CRLF
"INICIAR GPS"CRLF
"J\xc3\x81 CONECTADO A "CRLF
"DEFINIDO PARA"CRLF
"CONTRA-DIFUS\xc3\x83""O ISOB\xc3\x81""RICA"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"L\xc3\x8d""NGUA"CRLF
"\xc3\x9a""LTIMA CAL"CRLF
"\xc3\x9a""LTIMO MERGULHO"CRLF
"\xc3\x9a""LTIMO"CRLF
"\xc3\x9a""LTIMO GAS"CRLF
"PROF. \xc3\x9a""LT. PATA."CRLF
"LIMITE"CRLF
"CONECTADO"CRLF
"TMT LIGADO"CRLF
"LOCALIZA\xc3\x87\xc3\x83""O APAGADA"CRLF
"LOCALIZA\xc3\x87\xc3\x83""O GUARDADA"CRLF
"REGISTOS"CRLF
"LIGA\xc3\x87\xc3\x83""O PERDIDA"CRLF
"TMT DESCONECTADO"CRLF
"BATERIA"CRLF
"BATERIA FRACA"CRLF
"PO2 BAIXA"CRLF
"SP BAIXO"CRLF
"TEMP M\xc3\x8d""N"CRLF
"M\xc3\x8a""S.DIA"CRLF
"M/D/A"CRLF
"MAGENTA"CRLF
"ECR\xc3\x83 PRINCIPAL"CRLF
"MENU PRINCIPAL"CRLF
"FABRICANTE"CRLF
"MAX"CRLF
"PROF MAX"CRLF
"PROF MAX"CRLF
"PROF"CRLF
"MAX"CRLF
"T-MERGULHO MAX"CRLF
"ALTITUDE MAX"CRLF
"PO2 MAX."CRLF
"M\xc3\x89""DIO"CRLF
"M\xc3\x89""TRICO"CRLF
"MIN"CRLF
"MIN:SEG"CRLF
"DESCOMPRESS\xc3\x83""O OMISSA"CRLF
"MOD"CRLF
"MODO"CRLF
"MODELO"CRLF
"MAIS DADOS"CRLF
"MAIS DADOS"CRLF
"MINHA INFORMA\xc3\x87\xc3\x83""O"CRLF
"USE DIVERLOG+ APP"CRLF
"PARA CARREGAR O "CRLF
"FICHEIRO DE IMAGEM"CRLF
" "CRLF
"TL"CRLF
"N2"CRLF
"AL BAR N2"CRLF
"NOVO"CRLF
"NOVO OU CONT\xc3\x8d""NUO"CRLF
"SEGUINTE"CRLF
"BARRA DE AZOTO"CRLF
"N\xc3\x83""O"CRLF
"SEM DECO"CRLF
"TEMPO SEM DESCO"CRLF
"SEM IMERS\xc3\x95""E."CRLF
"C\xc3\x89""LULA O2 N\xc3\x83""O ENCONTRADA"CRLF
"LIGUE A C\xc3\x89""LULA DE"CRLF
"O2"CRLF
"SEM VISOR"CRLF
"SEM TMT"CRLF
" "CRLF
"SEM MERGULHO"CRLF
" "CRLF
"N\xc3\x83""O DISPON\xc3\x8d""VEL"CRLF
"DISPONIVEL"CRLF
"ANALISADOR O2"CRLF
"O2 NARC\xc3\x93""TICO"CRLF
"SAT O2"CRLF
"SAT O2 (FINAL)"CRLF
"TEMPO O2"CRLF
"JUNTAR A LISTA DE"CRLF
"G\xc3\x81""S?"CRLF
"C\xc3\x89""LULA O2 ESGOTADA"CRLF
"LIGUE UMA C\xc3\x89""LULA DE"CRLF
"O2 NOVA"CRLF
"PRESS\xc3\x83""O SUPERF\xc3\x8d""CIE"CRLF
"PRONTO PARA"CRLF
"CALIBRAR"CRLF
"OC-L E OC-R"CRLF
"SER\xc3\x83""O DEFINIDOS PARA"CRLF
"25/45"CRLF
"CONTINUAR?"CRLF
"SELECIONE A LISTA DE G\xc3\x81""S"CRLF
"PARA COLOCAR"CRLF
"CALIBRA\xc3\x87\xc3\x83""O DA "CRLF
"C\xc3\x89""LULA DE O2"CRLF
"CONCLU\xc3\x8d""DA"CRLF
"CALIBRE A"CRLF
"C\xc3\x89""LULA DE O2"CRLF
"ANTES DA AN\xc3\x81""LISE "CRLF
"A LER VOLTAGEM "CRLF
"C\xc3\x89""LULA DE O2"CRLF
" "CRLF
"OC"CRLF
"OC-1"CRLF
"OC-2"CRLF
"OC-3"CRLF
"OC-4"CRLF
"OC-5"CRLF
"OC-6"CRLF
"OC PO2 DECO"CRLF
"OC-E"CRLF
"OC PO2 MAX"CRLF
"OC PO2 MIN"CRLF
"OC-D"CRLF
"DESLIG"CRLF
"LIG"CRLF
"LARANJA"CRLF
"EMPARELHAR"CRLF
"C\xc3\x93""DIGO"CRLF
"CALIBRA\xc3\x87\xc3\x83""O COM SUCESSO"CRLF
"PESSOAL"CRLF
"PLANEAMENTO"CRLF
"PO2"CRLF
"PO2 AL"CRLF
"PO2 < 0.17 N\xc3\x83""O "CRLF
"PODE SER ALTERADO"CRLF
"PO2 (MAX)"CRLF
"LIMITES PO2"CRLF
"PRIMIR/PRESS\xc3\x83""O"CRLF
"P ATM ATIVA\xc3\x87\xc3\x83""O"CRLF
"PRESS\xc3\x83""O"CRLF
"PRONTA"CRLF
"REFER\xc3\x8a""NCIA NCE"CRLF
"REPOR PROFUNDIDADE M\xc3\x89""DIA"CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"DEFINI\xc3\x87\xc3\x95""ES SER\xc3\x83""O "CRLF
"REINICIADAS"CRLF
"(DADOS DO MERGULHO SER\xc3\x83""O MANTIDOS)"CRLF
"TEM A CERTEZA?"CRLF
"REINICIAR DEFINI\xc3\x87\xc3\x95""ES"CRLF
"RESULTADO"CRLF
"RODAR E VIRAR EM V\xc3\x81""RIAS"CRLF
"DIRE\xc3\x87\xc3\x95""ES AT\xc3\x89 OUVIR BIPE"CRLF
" "CRLF
"AL RTI"CRLF
"AL RTI"CRLF
"T DECORRIDO"CRLF
"SAC"CRLF
"PATAMAR SEGURAN\xc3\x87""A"CRLF
"SALGADA"CRLF
"SALT WATER"CRLF
"TAXA DE AMOSTRAGEM"CRLF
"- GUARDAR"CRLF
"GUARDAR LOCALIZA\xc3\x87\xc3\x83""O ATUAL"CRLF
"GUARDAR LOCALIZA\xc3\x87\xc3\x83""O?"CRLF
"GUARDAR PERFIL"CRLF
"MAR"CRLF
"SEARCH"CRLF
"PESQUISA"CRLF
"A PROCURAR TMT"CRLF
"SEG"CRLF
"SEG"CRLF
"SELECIONE O G\xc3\x81""S A COLOCAR"CRLF
"N\xc3\x9a""MERO DE S\xc3\x89""RIE"CRLF
"DEFIN."CRLF
"DEFINIR ALARMES"CRLF
"SET BO GAS"CRLF
"DEFINIR CALIBRA\xc3\x87\xc3\x83""O"CRLF
"FO2 G\xc3\x81""S"CRLF
"DEFINIR DECLIN"CRLF
"DEFINIR GASES"CRLF
"DEFINIR GF"CRLF
"DEFINIR GF ALTO"CRLF
"CONFIGURAR MENU"CRLF
"DEFINIR SP"CRLF
"DEFINIR UTILIT\xc3\x81""RIOS"CRLF
"CONFIG"CRLF
"DEFINI\xc3\x87\xc3\x95""ES"CRLF
"REINICIADAS"CRLF
"CONFIGURA\xc3\x87\xc3\x83""O"CRLF
"MENU DEFINI\xc3\x87\xc3\x83""O"CRLF
"SIMULAR MERGULHO"CRLF
"VISOR"CRLF
"LENT."CRLF
"SM"CRLF
"SN:"CRLF
"SP"CRLF
"SP (ALTO-BAIXO)"CRLF
"ALTERAR SP"CRLF
"DESPORTIVO"CRLF
"STANDARD"CRLF
"INICIAR"CRLF
"HORA DE IN\xc3\x8d""CIO"CRLF
"STOP"CRLF
"T PARAGEM"CRLF
"RESUMO"CRLF
"TEMP. DE SUPERFI."CRLF
"TEMPO DE SUPERFICIE"CRLF
"ALTERAR BO\xcb\x83""CC"CRLF
"ALTERAR CC\xcb\x83""BO"CRLF
"PRESS\xc3\x83""O P/TROC."CRLF
"SWITCH TO"CRLF
"ALTERAR P/ PERSONAL"CRLF
"ALTERE FO2 PARA"CRLF
"ALTERAR P/ ALTO"CRLF
"ALTERAR P/ BAIXO"CRLF
"SYSTEM ERROR"CRLF
"P GARRAFA"CRLF
"P GARRAFA"CRLF
"DESTINO"CRLF
"LOCALIZA\xc3\x87\xc3\x83""O DESTINO"CRLF
"TEC"CRLF
"TEMP"CRLF
"O G\xc3\x81""S ATUAL"CRLF
"DEPOIS ATIVAR"CRLF
"HORA"CRLF
"FORMATO HORA"CRLF
"TEMPO LIMITE"CRLF
"ALARME DE TEMPO PARA EMERGIR"CRLF
"TEMPO"CRLF
"SATURA\xc3\x87\xc3\x83""O TECIDOS"CRLF
"TECIDOS"CRLF
"COR DOS T\xc3\x8d""TULOS"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT L"CRLF
"TMT BATERIA FRACA"CRLF
"TMT  N\xc3\x83""O DISPON\xc3\x8d""VEL"CRLF
"TMT 6"CRLF
"\xe2\x84\x96 S\xc3\x89""RIE"CRLF
"DEFINIR \xe2\x84\x96 S\xc3\x89""RIE"CRLF
"TMT ESTADO"CRLF
"TROCA DE TMT"CRLF
"A"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- TROCAR"CRLF
"- ALTERAR"CRLF
"MUITO FUNDO"CRLF
"MUITO R\xc3\x81""PIDO"CRLF
"TOTAL T DECO"CRLF
"TOTAL MERGULHOS"CRLF
"TEMPO TOTAL"CRLF
"TOTAL T DECORRIDO"CRLF
"TRANSMISSORES"CRLF
"TTS"CRLF
"PRESS\xc3\x83""O RETORNO/FIM/TROCAR"CRLF
"PRESS RETORNO"CRLF
"AL PRESS RET"CRLF
"PRESS\xc3\x83""O DE RETORNO"CRLF
"PRESS\xc3\x83""O RETORNO/FINAL"CRLF
"ALARMES PRESS\xc3\x83""O FINAL/RETORNO"CRLF
"TIPO"CRLF
"DEBAIXO DE \xc3\x81""GUA"CRLF
"  "CRLF
"UNIDADES"CRLF
"- PARA CIMA"CRLF
"DEFINIDO 1"CRLF
"DEFINIDO 1"CRLF
"DEFINIDO 1"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"UTILIT\xc3\x81""RIOS"CRLF
"VALOR"CRLF
"VIBRA\xc3\x87\xc3\x83""O"CRLF
"VIOLA\xc3\x87\xc3\x83""O"CRLF
"AGUARDE SINAL BEEP,"CRLF
"AVISO"CRLF
"ATEN\xc3\x87\xc3\x83""O! GAS HIPOXICO"CRLF
"AVISO - BATERIA FRACA"CRLF
"ATEN\xc3\x87\xc3\x83""O! PO2 >1.60"CRLF
"TIPO DE \xc3\x81""GUA"CRLF
"BUSCA DE DIRE\xc3\x87\xc3\x95""ES"CRLF
"ECR\xc3\x83 BOAS-VINDAS"CRLF
"BRANCO"CRLF
"SER\xc3\x83""O DEFINIDOS PARA"CRLF
"WOB"CRLF
"ALARME WOB"CRLF
"TRABALHO VENTILAT\xc3\x93""RIO"CRLF
"SIM"CRLF
"CHEGOU AO SEU DESTINO"CRLF
};