#include"TxtStr_Order_DSX.h"
const char LangStr_Czech[] = {
"3 RADEK VLEVO"CRLF
"4 RADEK VPRAVO"CRLF
"AKTUALNI\xc2\xa0"""CRLF
"PO2/MOD"CRLF
"UPRAVIT"CRLF
"VZDUCH"CRLF
"ALARM"CRLF
"ALARM SLABA BATERIE"CRLF
"ALARMY"CRLF
"ANALYZOVAT"CRLF
"ANALYZ\xc3\x89""R"CRLF
"PROB\xc3\x8d""H\xc3\x81 ANAL\xc3\x9d""ZA"CRLF
"RV"CRLF
"VYST"CRLF
"PRILIS RYCHL\xc3\x9d V\xc3\x9d""STUP"CRLF
"ZVUKOVY ALARM"CRLF
"ZVUKOVY ALARM"CRLF
"ZVUK/VIBRACE"CRLF
"AUTO"CRLF
"AUTO ZTMAV."CRLF
"AUTO VYSOKY"CRLF
"AUTO NIZKY"CRLF
"PR\xc5\xae""M. SPOT\xc5\x98""."CRLF
"PRUM.HL."CRLF
"PRUM. HLOBUK."CRLF
"PRUM. D-PONORU"CRLF
"AVG.SAC"CRLF
"PRUM. TEPLOTA"CRLF
"BAILOUT PLYN SPOTREBA"CRLF
"Z\xc3\x81""CHRANN\xc3\x9d PL\xc3\x81""N"CRLF
"BAILOUT pO2 LIMITY"CRLF
"BAR"CRLF
"BATERIE OK"CRLF
"NEDOSTUPNY"CRLF
"BATERIE"CRLF
"BATTERY TOO LOW"CRLF
"PRAZDNY"CRLF
"BLUETOOTH"CRLF
"BT-JMENO"CRLF
"BLUETOOTH"CRLF
"PAROVANI"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"JAS"CRLF
"KALKULUJ\xc3\x8d""C\xc3\x8d"""CRLF
"KALIBROVAT"CRLF
"OPAKOVAT KALIBRACI"CRLF
"KALIBROV\xc3\x81""NO NA Z\xc3\x81""KLAD\xc4\x9a"""CRLF
"NELZE NASTAVIT"CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"CC-6 TLAK"CRLF
"CC- TLAK"CRLF
"CASOVAC"CRLF
"DEKO STROP"CRLF
"NAP\xc4\x9a""T\xc3\x8d \xc4\x8c""IDLA"CRLF
"ZM\xc4\x9a""NIT C\xc3\x8d""LOV\xc3\x89 UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d"CRLF
"NAB\xc3\x8d""T"CRLF
"STOPKY"CRLF
"VYNULOVAT TKANE"CRLF
"COMMUNICATION"CRLF
"KOMPAS"CRLF
"KOMPAS \xc2\xa0""NABIDKA"CRLF
"POTVRDIT?"CRLF
"PRIPOJIT"CRLF
"PRIPOJENO"CRLF
"PRIPOJEN - BLUETOOTH"CRLF
"PRIPOJENI"CRLF
"KONZERVATISMUS"CRLF
"KONZERVATISMUS - SPORT"CRLF
"KONZERVATISMUS- TEC"CRLF
"SPOTREBA"CRLF
"CONT."CRLF
"ODPOCET"CRLF
"AKTU\xc3\x81""LN\xc3\x8d UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d"CRLF
"AKTUALNI PO2"CRLF
"AKTUALNI TLAK"CRLF
"VLASTNI SP"CRLF
"TYRKYSOV\xc3\x81"""CRLF
"DEN/MESIC/ROK"CRLF
"DATA"CRLF
"DATA 1"CRLF
"DATA 2"CRLF
"DATA 3"CRLF
"DATUM"CRLF
"FORMAT DATUMU"CRLF
"DATUM & CAS"CRLF
"POCITAC"CRLF
"INFO O POCITACI"CRLF
"VYCHOD"CRLF
"V"CRLF
"NORTH"CRLF
"S"CRLF
"SOUTH"CRLF
"J"CRLF
"WEST"CRLF
"Z"CRLF
"DEKO PONOR"CRLF
"DEKO PONOR"CRLF
"VSTUP DO DEKO"CRLF
"DECO PO2"CRLF
"DEKO ZASTAVKY"CRLF
"- SNIZENI"CRLF
"DS"CRLF
"SMAZAT UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d""?"CRLF
"OBR\xc3\x81""ZEK"CRLF
"BUDE SMAZ\xc3\x81""N."CRLF
"CHCETE POKRA\xc4\x8c""OVAT?"CRLF
"SMAZ\xc3\x81""N."CRLF
"HLOUKA"CRLF
"HLOUKA"CRLF
"ALARM HLOUBKY"CRLF
"ALARM HLOUBKY"CRLF
"EKVIVALENTI NARKOTICKA HLOUBKA(END)"CRLF
"HYPOXICKY PRAH (HT)"CRLF
"MAX. PROVOZNI HLOUBKA(MOD)"CRLF
"DECHOVA PRACE(WOB)"CRLF
"HLOUBKOVE LIMITY"CRLF
"DESAT"CRLF
"NASTAVENI"CRLF
"Dil PO2"CRLF
"M\xc3\x8d""RA ZTMAVEN\xc3\x8d"""CRLF
"DISPLEJ"CRLF
"NASTAVEN\xc3\x8d OBRAZOVKY"CRLF
"VZD\xc3\x81""LENOST"CRLF
"DATA O PONORU"CRLF
"NABIDKA PONORU"CRLF
"REZIM PONORU"CRLF
"PLANOVAC PONORU"CRLF
"PLANOVAC"CRLF
"GRAF PONORU"CRLF
"NASTAVENI PONORU"CRLF
"DEKOMPRESN\xc3\x8d DOBA"CRLF
"> 99 MIN"CRLF
"SIMULATOR PONORU"CRLF
"D. PONORU"CRLF
"ALARM DOBY PONORU"CRLF
"DOBY PONORU/TTS"CRLF
"ALARMY DOBY PONORU/TTS"CRLF
"PONORY"CRLF
"MAXIMALNI CEILING "CRLF
"PRESAHUJE 400 FT "CRLF
"PRESAHUJE 120M"CRLF
"POCITAM"CRLF
" "CRLF
"DEN.MESIC"CRLF
"NEPREPINAT NA"CRLF
"- DOLU"CRLF
"DOLU NA ZASTAVKU"CRLF
"DS - PREHLED"CRLF
"DSX INFORMACE"CRLF
"DTR"CRLF
"ALARM ZBYV.D.PON."CRLF
"ZNACKA APLIKOVANA"CRLF
"ZNACKA"CRLF
"APLIKOVANA"CRLF
"NADM.VYSKA"CRLF
"EN13319"CRLF
"KONEC"CRLF
"ALARM END"CRLF
"KONCOVY TLAK"CRLF
"ALARM TLAK LAH."CRLF
"KONECNY TLAK V LAHVI"CRLF
"END/WOB/ICD"CRLF
"END/WOB/ICD ALARMY"CRLF
"ZAPIS"CRLF
"EKVIVALENTI NARKOTICKA HLOUBKA"CRLF
"ERROR"CRLF
"CHYBA"CRLF
"ALTITUDE"CRLF
"CHYBA"CRLF
"A TO D"CRLF
"CHYBA"CRLF
"KALIBRACE"CRLF
"CHYBA"CRLF
"CHECK SUM"CRLF
"CHYBA"CRLF
"EEPROM"CRLF
"CHYBA"CRLF
"POSLEDNI PONOR"CRLF
" "CRLF
"OPUSTIT WAYFINDER"CRLF
"CAS UKONCENI"CRLF
"EXTRA VELKY"CRLF
"NEUSPESNA"CRLF
"RYCH."CRLF
"FHE NEMUZE BYT"CRLF
"NASTAVEN NA 0 "CRLF
"ZATIMCO FO2 < 21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"OBRACENA OBR."CRLF
"NELITAT"CRLF
"FO2"CRLF
"SLADKA"CRLF
"PLYN"CRLF
"PLYN 1"CRLF
"PLYN 2"CRLF
"PLYN 3"CRLF
"PLYN 4"CRLF
"SPOTREBY PLYNU"CRLF
"PREPNUTI DYCHACI SMESI"CRLF
"DOBA DYCHACI SMESI"CRLF
"ZBYV.PLYN 5 MIN"CRLF
"HLOUBKOMER"CRLF
"HLOUBKOM. SM"CRLF
"GF"CRLF
"GF DOLNI"CRLF
"GF (NEJVYSSI)"CRLF
"GF HORNI"CRLF
"GF/N2"CRLF
"VYBRANY GF"CRLF
"GFBG"CRLF
"GFBG NEBO N2 BAR"CRLF
"NAVIGOVAT DO UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d""?"CRLF
"NAHORU"CRLF
"GPS"CRLF
"SMAZAT UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d"""CRLF
"NAB\xc3\x8d""DKA GPS"CRLF
"ABYSTE ULO\xc5\xbd""ILI NOV\xc3\x89"""CRLF
"UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d"", MUS\xc3\x8d""TE "CRLF
"VYMAZAT ST\xc3\x81""VAJ\xc3\x8d""C\xc3\x8d"""CRLF
"SIGN\xc3\x81""L GPS"CRLF
"NENALEZEN"CRLF
"\xc4\x8c""EK\xc3\x81""N\xc3\x8d NA"CRLF
"SIGN\xc3\x81""L GPS"CRLF
"ZELENA"CRLF
"ZB.PLYN"CRLF
"ZBYV.PLYN PRO L & P"CRLF
"VYSOK\xc3\x9d"""CRLF
"VYSOKY PO2"CRLF
"VYSOKY SP"CRLF
"HISTORIE"CRLF
"PRUM.HLOUB."CRLF
"NEJNIZSI TEPLOTA"CRLF
"MAX. HLOUBKA"CRLF
"MAX. DOBA PONORU"CRLF
"MAX. NADMORSKA VYSKA"CRLF
"CELKOVA DOBA PONORU"CRLF
"VYCHOZI NABIDKA"CRLF
"VYCHOZI NABIDKA"CRLF
"HODIN"CRLF
"HOD:MIN"CRLF
"ICD"CRLF
"ICD ALARMY"CRLF
"PROPOJITE-LI JE S"CRLF
"ANGLOS.JED."CRLF
"- ZVYSENI"CRLF
"INFO"CRLF
"INICIALIZACE"CRLF
"INICIALIZACE GPS"CRLF
"JE PROPOJEN S"CRLF
"JE NASTAVEN NA"CRLF
"IZOBARICKA PROTIDIFUZE"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"JAZYK"CRLF
"POSLEDNI KALIBRACE"CRLF
"POSL.PONOR"CRLF
"INFO POSL.PONOR"CRLF
"POSL.PLYN"CRLF
"POSLEDNI ZASTAVKA"CRLF
"LIMIT"CRLF
"P\xc5\x98""IPOJEN\xc3\x89"""CRLF
"TMT PROPOJEN"CRLF
"UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d SMAZ\xc3\x81""NO"CRLF
"UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d ULO\xc5\xbd""ENO"CRLF
"DENIK"CRLF
"ZTRATA SPOJENI"CRLF
"ZTRATA VYSILACE"CRLF
"SLABA"CRLF
"SLABA BATERIE"CRLF
"NIZKE PO2"CRLF
"NIZKY SP"CRLF
"MIN. TEPLOTA"CRLF
"MESIC.DEN"CRLF
"MESIC.DEN.ROK"CRLF
"PURPUROVA"CRLF
"HLAVNI DISPLEJ"CRLF
"HLAVNI NABIDKA"CRLF
"V\xc3\x9d""ROBCE"CRLF
"MAX."CRLF
"MAX HL"CRLF
"MAX.HLOUBKA"CRLF
"MAX."CRLF
"HLOUBKA"CRLF
"MAX D-PONORU"CRLF
"MAX. NADM. V."CRLF
"MAX. PO2"CRLF
"ST\xc5\x98""EDN\xc3\x8d"""CRLF
"METR.JEDN."CRLF
"MIN"CRLF
"MIN:S"CRLF
"VYNECHANA DEKOMPRESNI ZASTAVKA"CRLF
"MOD"CRLF
"REZIM"CRLF
"MODEL"CRLF
"VICE UDAJU"CRLF
"MAIS DADOS"CRLF
"MOJE INFORMACE"CRLF
"POU\xc5\xbd""IJTE APLIKACI DIVERLOG+"CRLF
"K NAHR\xc3\x81""N\xc3\x8d VA\xc5\xa0""EHO"CRLF
"INFORMA\xc4\x8c""N\xc3\x8d""HO SOUBORU"CRLF
" "CRLF
"N2"CRLF
"N2 GRAF"CRLF
"ALARM DUSIKU"CRLF
"NOV\xc3\x9d"""CRLF
"NOV\xc3\x9d NEBO KONTIN."CRLF
"DALSI"CRLF
"NITROGEN"CRLF
"NE"CRLF
"BEZ DEKO PON"CRLF
"BEZDEKOMPRESNI DOBA"CRLF
"ZADNY PONOR"CRLF
"O2 \xc4\x8c""IDLO NENALEZENO"CRLF
"P\xc5\x98""IPOJTE PROS\xc3\x8d""M"CRLF
"O2 \xc4\x8c""IDLO"CRLF
"NEDOSTUPN\xc3\x9d"""CRLF
"NEN\xc3\x8d TMT"CRLF
" "CRLF
"ZADNY PONOR"CRLF
" "CRLF
"NEDOSTUPNY"CRLF
"NOT AVAIL"CRLF
"ANALYZ\xc3\x89""R O2"CRLF
"O2 NARKOTIKUM"CRLF
"O2 SAT"CRLF
"O2 SAT (KONEC)"CRLF
"O2 CAS"CRLF
"P\xc5\x98""IDAT ANALYZOVAN\xc3\x9d PLYN"CRLF
"DO SEZNAMU PLYN\xc5\xae""?"CRLF
"O2 \xc4\x8c""IDLO VY\xc4\x8c""ERPAN\xc3\x89"""CRLF
"P\xc5\x98""IPOJTE PROS\xc3\x8d""M"CRLF
"NOV\xc3\x89 O2 \xc4\x8c""IDLO"CRLF
"TLAK NA POVRCHU"CRLF
"P\xc5\x98""IPRAVEN NA"CRLF
"KALIBRACI"CRLF
"OC-L I OC-R"CRLF
"BUDOU NASTAVENY NA"CRLF
"25/45"CRLF
"POKRA\xc4\x8c""OVAT?"CRLF
"VYBERTE SEZNAM PLYN\xc5\xae"""CRLF
"K P\xc5\x98""I\xc5\x98""AZEN\xc3\x8d "CRLF
"KALIBRACE"CRLF
"O2 \xc4\x8c""IDLA"CRLF
"DOKON\xc4\x8c""ENA"CRLF
"P\xc5\x98""ED ANAL\xc3\x9d""ZOU"CRLF
"PROS\xc3\x8d""M ZKALIBRUJTE"CRLF
"O2 \xc4\x8c""IDLO "CRLF
"DETEKCE NAP\xc4\x9a""T\xc3\x8d"""CRLF
"O2 \xc4\x8c""IDLA"CRLF
" "CRLF
"OC"CRLF
"OC-1"CRLF
"OC-2"CRLF
"OC-3"CRLF
"OC-4"CRLF
"OC-5"CRLF
"OC-6"CRLF
"OC DEKO PO2"CRLF
"OC-L"CRLF
"OC MAX. PO2"CRLF
"OC MIN. PO2"CRLF
"OC-P"CRLF
"VYP."CRLF
"ZAP."CRLF
"ORAN\xc5\xbd""OV\xc3\x9d"""CRLF
"PAROVANI"CRLF
"PASSCODE"CRLF
"KALIBRACE USPESNA"CRLF
"OSOBNI"CRLF
"PLANOVAC"CRLF
"PO2"CRLF
"PO2 AL"CRLF
"PO2 < 0.17 "CRLF
"PREPNUTI NEMOZNE"CRLF
"PO2 (NEJVYSSI)"CRLF
"LIMITY pO2\xc2\xa0"""CRLF
"TLAK"CRLF
"TLAK PRI AKTIVACI"CRLF
"TLAK"CRLF
"PRIPRAVEN"CRLF
"REFERENCE"CRLF
"RESET PR\xc5\xae""M\xc4\x9a""RN\xc3\x89 HLOUBKY"CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"NASTAVENI BUDOU"CRLF
"RESETOVANY"CRLF
"(\xc3\x9a""DAJE O PONORU BUDOU ZACHOV\xc3\x81""NY)"CRLF
"JSTE SI JISTY?"CRLF
"RESET NASTAVENI"CRLF
"V\xc3\x9d""SLEDEK"CRLF
"ROTOVAT A OTACET"CRLF
"VICE SMERY AZ"CRLF
"DO PIPNUTI"CRLF
"ALARM RTI"CRLF
"ALARM RTI"CRLF
"\xc4\x8c""AS"CRLF
"SAC"CRLF
"SS"CRLF
"SLANA"CRLF
"SALT WATER"CRLF
"FREKVENCE ZAZNAMU"CRLF
"- ULOZIT"CRLF
"ULO\xc5\xbd""IT AKTU\xc3\x81""LN\xc3\x8d UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d"CRLF
"ULO\xc5\xbd""IT UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d?"CRLF
"SAVING DIVE PROFILE"CRLF
"MORE"CRLF
"SEARCH"CRLF
"VYHLED\xc3\x81""V\xc3\x81""N\xc3\x8d"""CRLF
"HLEDAT VYSILAC"CRLF
"SEC"CRLF
"SEGMENTY"CRLF
"VYBERTE PLYN K P\xc5\x98""I\xc5\x98""AZEN\xc3\x8d"""CRLF
"VYROBNI CISLO"CRLF
"NAST."CRLF
"NASTAVENI ALARMU"CRLF
"SET BO GAS"CRLF
"NASTAVIT FO2"CRLF
"KALIBRA\xc4\x8c""N\xc3\x8d""HO PLYNU"CRLF
"NASTAVENI ODCHYLKY"CRLF
"NASTAVENI PLYNU"CRLF
"NASTAVENI GF"CRLF
"NASTAVIT HORNI GF"CRLF
"NABIDKA NASTAVENI"CRLF
"NASTAVIT SP"CRLF
"NASTAVENI PARAMETRU"CRLF
"NASTAVENI"CRLF
"NASTAVENI BYLY"CRLF
"RESETOVANY"CRLF
"NASTAVENI"CRLF
"NABIDKA NASTAV."CRLF
"SIMULOVAT PONOR"CRLF
"TABULKY"CRLF
"POMA."CRLF
"SM"CRLF
"SN:"CRLF
"SP"CRLF
"SP (NEJVYSSI-NEJNIZSI)"CRLF
"PREPNOUT SP"CRLF
"SPORT"CRLF
"STANDARD"CRLF
"ZAHAJENI"CRLF
"CAS ZAHAJENI"CRLF
"DEKO"CRLF
"ZASTAVKA"CRLF
"SOUHRN"CRLF
"POVRCHOVY"CRLF
"POVRCHOVY INTERVAL"CRLF
"PREPNUTI BO\xcb\x83""CC"CRLF
"PREPNUTI CC\xcb\x83""BO"CRLF
"TLAK P\xc5\x98""EPNUT\xc3\x8d PLYNU"CRLF
"PREPNUTI NA"CRLF
"PREPNOUT NA VLASTNI"CRLF
"PREPNOUT NA FO2"CRLF
"PREPNOUT NA VYSOKY"CRLF
"PREPNOUT NA NIZKY"CRLF
"SYSTEM ERROR"CRLF
"TLAK V LAHVI"CRLF
"TLAK V LAHVI"CRLF
"C\xc3\x8d""L"CRLF
"C\xc3\x8d""LOV\xc3\x89 UM\xc3\x8d""ST\xc4\x9a""N\xc3\x8d"CRLF
"TEC"CRLF
"TEPLOTA"CRLF
"SOU\xc4\x8c""ASN\xc3\x9d PLYN"CRLF
"POTOM AKTIVOVAT"CRLF
"CAS"CRLF
"FORMAT CASU"CRLF
"\xc4\x8c""AS LIMITY"CRLF
"ALARM DOBY DO VYNO\xc5\x98""EN\xc3\x8d"""CRLF
"\xc4\x8c""AS DO ZTMAVEN\xc3\x8d"""CRLF
"NASYCENI TKANI"CRLF
"TKANE"CRLF
"BARVA NAPISU"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT L"CRLF
"VYS.SLABA BATERIE"CRLF
"VYSILAC NEDOSTUPNY"CRLF
"TMT 6"CRLF
"S\xc3\x89""RIOV\xc3\x89 \xc4\x8c""."CRLF
"NAST. S\xc3\x89""RIOV\xc3\x89 \xc4\x8c""."CRLF
"STAV VYSILACU"CRLF
"PREPNUT\xc3\x8d VYSILACE"CRLF
"DO"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- PREPNOUT"CRLF
"- PREPINANI"CRLF
"PRILIS HLUBOKO"CRLF
"PRILIS RYCHLE"CRLF
"CELKOVE DEKO"CRLF
"CELKEM PONORU"CRLF
"CELK. DOBA PONORU"CRLF
"CELKOVY CAS/RUNTIME"CRLF
"VYSILACE"CRLF
"TTS"CRLF
"TLAK OTOC./UK./PREP."CRLF
"TLAK OBRATU"CRLF
"ALARM OBR.PON"CRLF
"TLAK OTOCENI PONORU"CRLF
"ALARM TLAKU"CRLF
"ALARM TLAKU V LAHVI"CRLF
"TYP"CRLF
"POD VODOU"CRLF
" "CRLF
"JEDNOTKY"CRLF
"- NAHORU"CRLF
"NAHRANO 1"CRLF
"NAHRANO 2"CRLF
"NAHRANO 3"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"PARAMETRY"CRLF
"HODNOTA"CRLF
"VIBRACE"CRLF
"PORUSENI"CRLF
"CEKAT NA PIPNUTI,"CRLF
"VAROVANI"CRLF
"VAROVANI! HYPOXICKY PLYN"CRLF
"VAROVANI SLABA BATERIE"CRLF
"VAROVANI! PO2 > 1.60"CRLF
"TYP VODY"CRLF
"WAYFINDER"CRLF
"UVODNI OBRAZOVKA"CRLF
"BILA"CRLF
"BUDOU NASTAVENY"CRLF
"WOB"CRLF
"ALARM WOB"CRLF
"DECHOVA PRACE"CRLF
"ANO"CRLF
"DOS\xc3\x81""HLI JSTE SV\xc3\x89""HO C\xc3\x8d""LE"CRLF
};