#include"TxtStr_Order_DSX.h"
const char LangStr_Italian[] = {
"3\xc2\xb0 RIGA SINISTRA"CRLF
"3\xc2\xb0 RIGA DESTRA"CRLF
"ATTUALE"CRLF
"PO2/MOD "CRLF
"REGOLAZIONE"CRLF
"ARIA"CRLF
"ALLARME"CRLF
"ALLARME BATT SCARICA"CRLF
"ALLARMI"CRLF
"ANALIZZARE"CRLF
"ANALIZZATORE"CRLF
"ANALIZZANDO"CRLF
"VR"CRLF
"ASC"CRLF
"RISALITA RAPIDA\xc2\xa0"""CRLF
"ACUSTICO"CRLF
"AL ACUSTICO"CRLF
"ACUSTICO/VIBRAZIONE"CRLF
"ALTO"CRLF
"AUTO DIM"CRLF
" AUTO ALTO"CRLF
"AUTO BASSO"CRLF
"CONSUMO MEDIO"CRLF
"PROF MEDIA"CRLF
"PROF MEDIA"CRLF
"TEMPO MEDIO IMM"CRLF
"AVG.SAC"CRLF
"TEMP MEDIA"CRLF
"CONSUMO GAS BAILOUT"CRLF
"PLANO BAILOUT"CRLF
"LIMITE PO2 BAILOUT"CRLF
"BAR"CRLF
"BATT GOOD"CRLF
"BATT LOW"CRLF
"LA BATTERIA"CRLF
"BATTERY TOO LOW"CRLF
"VUOTO"CRLF
"BLUETOOTH"CRLF
"NOME BLUETOOTH"CRLF
"ABBINAMENTO"CRLF
"DEL BLUETOOTH"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"LUMINOSITA'"CRLF
"CALCOLO IN CORSO"CRLF
"CALIBRAZIONE"CRLF
"ESEGUIRE NUOVA CALIBRAZIONE"CRLF
"CALIBRATO IN BASE A"CRLF
"IL GAS ATTUALE"CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"CC-6 PRESS"CRLF
" PRESSIONE CC"CRLF
"CRT"CRLF
"TETTO"CRLF
"TENSIONE CELLA"CRLF
"CAMBIA DESTINAZIONE"CRLF
"CARICA"CRLF
"CRONO"CRLF
"RESET SATURAZIONE"CRLF
"COMUNICAZIONE"CRLF
"BUSSOLA"CRLF
"MENU BUSSOLA"CRLF
"CONFERMI?"CRLF
"CONNESSIONE"CRLF
"CONNESSO "CRLF
"CONNESSO - BLUETOOTH"CRLF
"CONNESSIONE"CRLF
"CONSERVATIVO"CRLF
"CONSERVATIVO - SPORT"CRLF
"CONSERVATIVO - TEC"CRLF
"CONSUMO "CRLF
"CONTINUA"CRLF
"CONTO ALLA ROVESCIA"CRLF
"POSIZIONE ATTUALE"CRLF
"PO2 ATTUALE"CRLF
"ATTUALE PRESSIONE"CRLF
"SP PERS."CRLF
"CIANO"CRLF
"GG/MM/AA"CRLF
"DATI"CRLF
"DATI 1"CRLF
"DATI 2"CRLF
"DATI 3"CRLF
"DATA"CRLF
"FORMATO DATA"CRLF
"DATA & ORA"CRLF
"DC"CRLF
"INFO COMPUTER"CRLF
"EAST"CRLF
"E"CRLF
"NORTH"CRLF
"N"CRLF
"SOUTH"CRLF
"S"CRLF
"WEST"CRLF
"W"CRLF
"DECO"CRLF
"DECO"CRLF
"INIZIO DECO"CRLF
"DECO PO2"CRLF
"DECO STOPS"CRLF
"- DIMINUIRE"CRLF
"DEEP STOP"CRLF
"ELIMINA POSIZIONE?"CRLF
"IMMAGINE"CRLF
"SAR\xc3\x80 CANCELLATA."CRLF
"SEI SICURO?"CRLF
"ELIMINATA."CRLF
"PROFONDITA'"CRLF
"PROF."CRLF
"AL PROF."CRLF
"AL PROFONDITA'"CRLF
"PROFONDITA' NARCOTICA EQUIVALEN.(END)"CRLF
"SOGLIA IPOSSICA(HT)"CRLF
"MASSIMA PROFONDITA' OPERATIVA(MOD)"CRLF
"LAVORO RESPIRATORIO(WOB)"CRLF
"LIMITE DI PROFONDTA'\xc2\xa0"""CRLF
"DESAT"CRLF
"IMPOSTAZIONI DISPOSITIVO "CRLF
"Dil PO2"CRLF
"REGOL.LUMIN."CRLF
"DISPLAY"CRLF
"IMPOSTAZIONE DISPLAY"CRLF
"DISTANZA"CRLF
"DATI IMM"CRLF
"MENU IMM"CRLF
"MODALITA'"CRLF
"SIMULATORE IMM"CRLF
"PIANIFICATORE IMMERSIONI"CRLF
"GRAFICO PROFILO"CRLF
"IMPOSTAZIONI IMM."CRLF
"TEMPO DECO"CRLF
"> 99 MIN"CRLF
"SIMULATORE IMM"CRLF
"TEMPO-IMM"CRLF
"ALL.  TEMPO IMM."CRLF
"TEMPO-IMM./TTS"CRLF
"ALLARMI TEMPO-IMM./TTS"CRLF
"IMMERSIONI"CRLF
"TETTO MASSIMO"CRLF
"SUPERATO 400 PIEDI"CRLF
"SUPERATO 120M"CRLF
"IL TEMPO PIANIFICATO PER LA DISCESA "CRLF
"ALLA MAX PROF. NON E\xe2\x80\x99 SUFFICIENTE"CRLF
"GG/MM"CRLF
"NON CAMBIARE"CRLF
"- FINE LISTA"CRLF
"VAI ALLO STOP"CRLF
"ANTEPRIMA SP"CRLF
"INFO DSX"CRLF
"SCARICARE"CRLF
"DTR"CRLF
"AL DTR"CRLF
"SEGNAPUNTO APPLICATO"CRLF
"SEGNAPUNTO"CRLF
"APPLICATO"CRLF
"ALTIT."CRLF
"EN13319"CRLF
"END"CRLF
"ALARME END"CRLF
"PRESS. FINALE"CRLF
"AL PRESS MIN"CRLF
"PRESSIONE FINALE"CRLF
"END/WOB/CDI"CRLF
"ALLARMI/END/WOB/CDI "CRLF
"ELENCO"CRLF
"PROF. NARCOTICA EQUIVALENTE"CRLF
"ERROR"CRLF
"ERRORE"CRLF
"ALTITUDE"CRLF
"ERRORE"CRLF
"A FINO A D"CRLF
"ERRORE"CRLF
"CALIBRAZIONE"CRLF
"ERRORE"CRLF
"CHECKSUM"CRLF
"ERRORE"CRLF
"EEPROM"CRLF
"ERRORE"CRLF
"ERRORE"CRLF
"IMMERSIONE"CRLF
"ESCI DA TROVA POSIZIONE"CRLF
"TEMPO DI USCITA"CRLF
"EXTRA LARGE "CRLF
"FALLITA"CRLF
"RAPID."CRLF
"FHE NON PUO' ESSERE"CRLF
"IMPOSTATO SU 0"CRLF
"SE \xc2\xa0""FO2 < 21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"SCHERMO ROVESCIATO "CRLF
"VOLO"CRLF
"FO2"CRLF
"DOLCE"CRLF
"GAS"CRLF
"GAS 1"CRLF
"GAS 2"CRLF
"GAS 3"CRLF
"GAS 4"CRLF
"CONSUMO GAS "CRLF
"CAMBIO GAS"CRLF
"TEMPO RESIDUO GAS"CRLF
"GAS TEMPO RESIDUO \xc2\xa0""5 MIN"CRLF
"MANOMETRO"CRLF
"MANOMET. SM"CRLF
"GF"CRLF
"GF ALTO"CRLF
"GF (ALTO)"CRLF
"GF BASSO"CRLF
"GF/N2"CRLF
"GF SELEZIONATI"CRLF
"GFBG"CRLF
"GRAFICO GF O N2"CRLF
"VAI ALLA POSIZIONE?"CRLF
"RISALI"CRLF
"GPS"CRLF
"CANCELLA POSIZIONE"CRLF
"MENU GPS "CRLF
"DEVI CANCELLARE UNA POSIZIONE"CRLF
"PER SALVARE UNA NUOVA POSIZIONE"CRLF
" "CRLF
"SEGNALE GPS "CRLF
"NON TROVATO"CRLF
"ASPETTA"CRLF
"SEGNALE GPS"CRLF
"VERDE"CRLF
"GTR"CRLF
"GTR PER S & D "CRLF
"ALTO"CRLF
"PO2 ALTA"CRLF
"SP ALTO"CRLF
"STORICO"CRLF
"PROF. MEDIA"CRLF
"TEMP. MIN."CRLF
"PROF MAX"CRLF
"TEMPO-IMM MAX"CRLF
"ALTEZ.MAX"CRLF
"ORE TOTALI IMMERSIONI "CRLF
"HOME"CRLF
"MENU PRINCIPALE"CRLF
"H"CRLF
"H:MIN"CRLF
"ICD"CRLF
"ALLARMI CDI"CRLF
"SE LO COLLEGHI SU"CRLF
"IMPERIALE"CRLF
"- AUMENTARE"CRLF
"INFO"CRLF
"INIZIALIZZAZIONE"CRLF
"INIZIALIZZAZIONE GPS"CRLF
"\xc3\x88 GI\xc3\x80 COLLEGATO A"CRLF
"IS SET TO"CRLF
"CONTRO DIFFUSIONE ISOBARICA"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"LINGUA"CRLF
"ULTIMA CAL"CRLF
"VOLO"CRLF
"DATI ULTIMA IMM"CRLF
"ULTIMO GAS"CRLF
"PROF. ULTIMA TAPPA"CRLF
"LIMITE"CRLF
"CONNESSO"CRLF
"CONNESSO TMT"CRLF
"DESTINAZIONE CANCELLATA"CRLF
"POSIZIONE SALVATA"CRLF
"MEMORIA"CRLF
"COLLEGAMENTO PERSO"CRLF
"TMT PERDUTO\xc2\xa0"""CRLF
"BATT"CRLF
"BATT SCARICA"CRLF
"PPO2 BASSA"CRLF
"SP BASSO"CRLF
"TEMP. MINIMA\xc2\xa0"""CRLF
"MM/GG"CRLF
"MM/GG/AA"CRLF
"MAGENTA"CRLF
"DISPLAY PRICNIPALE"CRLF
"MENU PRINCIPALE"CRLF
"PRODUTTORE"CRLF
"MAX"CRLF
"PROF.MAX"CRLF
"PROF.MAX"CRLF
"PROF"CRLF
"MAX "CRLF
"TEMPO-IMM MAX"CRLF
"MAX ALT"CRLF
"MAX PO2"CRLF
"MEDIUM"CRLF
"METRICO"CRLF
"MIN"CRLF
"MIN:SEC"CRLF
"DECO OMESSA"CRLF
"MOD"CRLF
"MODALITA'"CRLF
"MODELLO "CRLF
"ALTRI DATI"CRLF
"ALTRI DATI IMM"CRLF
"MIE INFO"CRLF
"UTILIZZA L'APP DIVERLOG+"CRLF
"PER  CARICARE IL TUO "CRLF
"FILE IMMAGINE  INFO"CRLF
" "CRLF
"N2"CRLF
"N2 BAR"CRLF
"AL N2 BAR"CRLF
"NUOVO"CRLF
"NUOVO O CONTINUA"CRLF
"AVANTI"CRLF
"AZOTO"CRLF
"NO"CRLF
"NO DECO"CRLF
"LIMITE NON DECO"CRLF
"NESSUNA"CRLF
"NESSUNA CELLA O2 TROVATA"CRLF
"SI PREGA DI CONNETTERSI"CRLF
"CELLA O2"CRLF
"NESSUNA IMMAGINE"CRLF
"NO TMT "CRLF
"NESSUNA"CRLF
"IMMERSIONE"CRLF
"REGISTRATA"CRLF
"NON DISP"CRLF
"NON DISP"CRLF
"ANALIZZATORE O2"CRLF
"O2 NARCOTICO"CRLF
"SAT. O2"CRLF
"SAT. O2 (FINALE)"CRLF
"O2 TIME"CRLF
"AGGIUNGI GAS ANALIZZATO"CRLF
"A UNA LISTA GAS?"CRLF
"NESSUNA CELLA O2 TROVATA"CRLF
"SI PREGA DI CONNETTERSI"CRLF
"CELLA O2"CRLF
"PRESSIONE IN SUPERFICIE"CRLF
"PRONTA PER"CRLF
"CALIBRAZIONE"CRLF
"ENTRAMBI OC-L E OC-R"CRLF
"SARANNO IMPOSTATI SU"CRLF
"25/45"CRLF
"PROCEDERE?"CRLF
"SELEZIONA ELENCO GAS"CRLF
"DA ASSEGNARE"CRLF
"CELLA O2"CRLF
"CALIBRAZIONE"CRLF
"COMPLETA"CRLF
"PER FAVORE CALIBRARE"CRLF
"O2 CELLA"CRLF
"PRIMA DI ANALIZZARE"CRLF
"LETTURA TENSIONE "CRLF
"CELLA O2"CRLF
" "CRLF
"CA"CRLF
"CA-1"CRLF
"CA-2"CRLF
"CA-3"CRLF
"CA-4"CRLF
"CA-5"CRLF
"CA-6"CRLF
"CA PO2 DECO"CRLF
"CA-S"CRLF
"CA PO2 MAX."CRLF
"CA PO2 MIN."CRLF
"CA-D"CRLF
"OFF "CRLF
"ON"CRLF
"ARANCIA"CRLF
"ABBINAMENTO"CRLF
"CODICE DI ACCESSO"CRLF
"CALIBRAZIONE ESEGUITA"CRLF
"PERSONALI"CRLF
"PLANNER"CRLF
"PO2"CRLF
"PO2 AL"CRLF
"PO2 < 0.17 "CRLF
"CAMBIO NON PERMESSO"CRLF
"PO2 (MASSIMA)"CRLF
"LIMITI PO2"CRLF
"PRESS"CRLF
"PRES.ALL'ATTIVAZIONE"CRLF
"PRESSIONE"CRLF
"COMPLETATA"CRLF
"RIFERIMENTO"CRLF
"RESET PROFONDIT\xc3\x80 MEDIA"CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"SETTINGS WILL"CRLF
"BE RESET TO DEFAULTS"CRLF
"(MEMORIZZAZIONE DATI IMMERSIONE)"CRLF
"SEI SICURO ?"CRLF
"RESETTARE IMPOSTAZIONI"CRLF
"RISULTATO"CRLF
"RUOTARE E CAPOVOLGERE"CRLF
"IN DIREZIONI MULTIPLE"CRLF
"FINO AL BIP"CRLF
"AL RTI"CRLF
"ALLARME RTI"CRLF
"TEMPO TOTALE"CRLF
"SAC"CRLF
"SOST.SIC"CRLF
"SALATA"CRLF
"SALT WATER"CRLF
"CAMPIONAMENTO"CRLF
"- SALVA"CRLF
"SALVA POSIZIONE ATTUALE"CRLF
"SALVARE LA POSIZIONE?"CRLF
"SALVANDO IL PROFILO"CRLF
"MARE"CRLF
"SEARCH"CRLF
"RICERCA"CRLF
"RICERCA TMT"CRLF
"SEC"CRLF
"SEGMENTI"CRLF
"SELEZIONA IL GAS DA ASSEGNARE"CRLF
"NO SERIE"CRLF
"IMP"CRLF
"IMP ALLARMI"CRLF
"SET BO GAS"CRLF
"IMPOSTAZI. CALIBRAZI."CRLF
"GAS FO2"CRLF
"IMP DECLIN"CRLF
"IMP GAS "CRLF
"IMPOSTAZIONI GF"CRLF
"IMP GF ALTO"CRLF
"MENU IMP"CRLF
"SETTAGGIO S.P."CRLF
"IMP UTILITA'"CRLF
"IMP."CRLF
"IMPOSTAZIONE"CRLF
"RESETTATE"CRLF
"IMPOSTAZIONI"CRLF
"MENU IMP"CRLF
"SIMULARE IMMERSIONE"CRLF
"IMMAGINI"CRLF
"LENTI"CRLF
"SM"CRLF
"NS:"CRLF
"SP"CRLF
"SP (ALTO-BASSO)"CRLF
"CAMBIO S.P."CRLF
"SPORT"CRLF
"STANDARD"CRLF
"INIZIO"CRLF
"ORA INIZIO"CRLF
"STOP"CRLF
"TEMPO STOP"CRLF
"RIEPILOGO"CRLF
"TEMPO DI SUP"CRLF
"TEMPO DI SUP"CRLF
"CAMBIA DA BO\xcb\x83""CC"CRLF
"CAMBIA DA CC\xcb\x83""BO"CRLF
"PRESS. CAMBIO"CRLF
"PASSA A"CRLF
"PASSA SU S.P. PERSONAL."CRLF
"CAMBIA A FO2"CRLF
"PASSA SU S.P. ALTO\xc2\xa0"""CRLF
"PASSA SU S.P. BASSO"CRLF
"SYSTEM ERROR"CRLF
"PRESSIONE BOMBOLA"CRLF
"PRESSIONE BOMBOLA"CRLF
"OBBIETTIVO"CRLF
"LOCALIT\xc3\x80 DI DESTINAZIONE"CRLF
"TEC"CRLF
"TEMP"CRLF
"IMPOSSIBILE IMPOSTARE"CRLF
"SONORO E DOPO ATTIVARE"CRLF
"ORA"CRLF
"FORMATO ORA"CRLF
"LIMITE DI TEMPO"CRLF
"ALLARLE TEMPO DI SUPERFICE"CRLF
"TEMP.ATTENUAZ.LUMIN."CRLF
"SATURAZIONE TESSUTI"CRLF
"TESSUTI"CRLF
"COLORE CARATTERI"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT S"CRLF
"BATT SCARICA TMT"CRLF
"TMT  NON DISPONIBLE"CRLF
"TMT R"CRLF
"SERIAL"CRLF
"SET SERIAL"CRLF
"STATO TMT "CRLF
"CAMBIO TMT"CRLF
"AL"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- CAMBIA GAS"CRLF
"- CAMBIA SEL"CRLF
"TROPPO PROFONDO"CRLF
"RISALITA RAPIDA"CRLF
"DECO TOTALE"CRLF
"NUMERO IMMERSIONI"CRLF
"TOT TEMPO-IMM"CRLF
"TEMPO TOTALE IMM"CRLF
"TRASMETTITORE"CRLF
"TTS"CRLF
"PRESS. RIENT./FINALE/CAM."CRLF
"PRESS. RIENTRO"CRLF
"AL GAS RIENTRO"CRLF
"LIMITE GAS DI RIENTRO"CRLF
"PRESS. RITORN / FINALE"CRLF
"ALLARMI PRESS. FINALE / RIENTRO\xc2\xa0"""CRLF
"TIPO"CRLF
"IMPOSTATO DURANTE"CRLF
"L'IMMERSIONE\xc2\xa0"""CRLF
"UNITA' DI MISURA"CRLF
"- INIZIO LISTA"CRLF
"CARICATO  1"CRLF
"CARICATO  2"CRLF
"CARICATO  3"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"UTILITA'"CRLF
"VALORE"CRLF
"VABRAZIONE"CRLF
"VIOLAZIONE"CRLF
"ATTENDERE IL SEGNALE"CRLF
"PERICOLO"CRLF
"PERICOLO ! GAS IPOSSICO"CRLF
"AVVISO BATTERIA"CRLF
"PERICOLO! PO2 >1.60"CRLF
"TIPO ACQUA"CRLF
"TROVA LA POSIZIONE"CRLF
"SCHERM. DI BENVENU."CRLF
"BIANCA"CRLF
"VERR\xc3\x80 IMPOSTO SENZA NESSUN"CRLF
"WOB"CRLF
"ALLARME WOB"CRLF
"LAVORO RESPIRATORIO "CRLF
"SI"CRLF
"HAI RAGGIUNTO IL TUO OBIETTIVO"CRLF
};