#include"TxtStr_Order_DSX.h"
const char LangStr_French[] = {
"LIGNE 3 GAUCHE"CRLF
"LIGNE 3 DROITE"CRLF
"ACTUEL"CRLF
"PPO2/MOD"CRLF
"AJUSTER"CRLF
"AIR"CRLF
"ALARMES"CRLF
"ALARM LOW BATT"CRLF
"ALARMES"CRLF
"ANALYSER"CRLF
"ANALYSEUR"CRLF
"ANALYSE EN COURS"CRLF
"VR"CRLF
"ASC"CRLF
"REMONTEE TROP VITE"CRLF
"AUDIBLE"CRLF
"ALARME AUDIBLE"CRLF
"AUDIBLE/VIBRATION"CRLF
"AUTO"CRLF
"AUTO-LUMI."CRLF
"AUTO SUP"CRLF
"AUTO INF"CRLF
"C. MOYENNE"CRLF
"PROF MOYENNE"CRLF
"PROF MOYENNE"CRLF
"T-PLONGEE MOYEN"CRLF
"SAC MOYEN"CRLF
"TEMP MOYENNE"CRLF
"CONSOM. DES GAZ DE SAUVETAGE"CRLF
"PLAN DE SAUVETAGE"CRLF
"LIMITES PPO2 SAUVETAGE"CRLF
"BAR"CRLF
"BONNE BATT"CRLF
"BATT LOW"CRLF
"LA BATTERIE"CRLF
"BATTERY TOO LOW"CRLF
"VIDE"CRLF
"BLUETOOTH"CRLF
"NOM BLUETOOTH"CRLF
"PAIRAGE"CRLF
"BLUETOOTH"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"LUMINOSITE"CRLF
"CALCUL EN COURS"CRLF
"CALIBRATION"CRLF
"RELANCEZ LA CALIBRATION"CRLF
"CALIBREE AVEC"CRLF
"NE PEUT PAS ETRE"CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"PRESS CC-6"CRLF
"PRESSION DE CC-6"CRLF
"CAR"CRLF
"PLAFOND"CRLF
"VOLTAGE DE LA CELLULE"CRLF
"CHANGER LA POSITION CIBLE"CRLF
"CHARGEZ"CRLF
"CHRONO"CRLF
"REINIT TISSUS"CRLF
"COMMUNICATION"CRLF
"COMPAS"CRLF
"MENU COMPAS"CRLF
"CONFIRMER?"CRLF
"CONNEXION"CRLF
"CONNECTE"CRLF
"CONNECTE - BLUETOOTH"CRLF
"CONNECTION"CRLF
"CONSERVATISME"CRLF
"CONSERVATISM - SPORT"CRLF
"CONSERVATISME - TEC"CRLF
"CONSOMMATION"CRLF
"CONTINUE"CRLF
"DECOMPTE"CRLF
"POSITION ACTUELLE"CRLF
"CURRENT PO2"CRLF
"PRESSION ACTUELLE"CRLF
"SP PER"CRLF
"CYAN"CRLF
"J/M/A"CRLF
"DONNEES"CRLF
"DONNEES 1"CRLF
"DONNEES 2"CRLF
"DONNEES 3"CRLF
"DATE"CRLF
"FORMAT DATE"CRLF
"DATE & HEURE"CRLF
"ORDINATEUR"CRLF
"INFOS ORDI"CRLF
"EST"CRLF
"E"CRLF
"NORTH"CRLF
"N"CRLF
"SOUTH"CRLF
"S"CRLF
"WEST"CRLF
"W"CRLF
"PALIER"CRLF
"PALIER"CRLF
"ENTREE PALIER"CRLF
"DECO PO2"CRLF
"PALIERS"CRLF
"- REDUIRE"CRLF
"PALIER PROF."CRLF
"SUPPRIME LA POSITION GPS?"CRLF
"IMAGE"CRLF
"SERA SUPPRIMEE."CRLF
"ETES-VOUS SUR?"CRLF
"EST SUPPRIMEE."CRLF
"PROF."CRLF
"PROF."CRLF
"AL PROF."CRLF
"AL PROF"CRLF
"PROF. EQUIVALENT NARCOTIQUE(END)"CRLF
"SEUIL HYPOXIQUE(SH)"CRLF
"PROFONDEUR MAX D'OPERATION(MOD)"CRLF
"TRAVAIL RESPIRATOIRE(WOB)"CRLF
"LIMITES DE PROFONDEUR"CRLF
"DESAT"CRLF
"PARAMETRES DE L'APPAREIL"CRLF
"PPO2 Dil."CRLF
"REDUIRE LUMINOSITE A"CRLF
"ECRAN"CRLF
"REGLAGES ECRAN"CRLF
"DISTANCE"CRLF
"DONNEES PLONGEE"CRLF
"MENU PLONGEE"CRLF
"MODE DE PLONGEE"CRLF
"PLAN DE PLONGEE"CRLF
"PLANIFICATEUR"CRLF
"GRAPH. PROFIL PLONGEE"CRLF
"REGLAGES PLONGEE"CRLF
"TEMPS DE PALIER"CRLF
"> 99 MIN"CRLF
"SIMULATEUR DE PLONGE"CRLF
"T-PLONGEE"CRLF
"AL TEMPS PLONGEE"CRLF
"T-PLONGEE/TTS"CRLF
"ALARMES T-PLONGEE/TTS"CRLF
"PLONGEES"CRLF
"PLAFOND MAXIMUM"CRLF
"AU-DEL\xc3\x80 DE 400 PIEDS"CRLF
"AU-DEL\xc3\x80 DE 120M"CRLF
"PAS ASSEZ DE TEMPS POUR "CRLF
"DESCENDRE"CRLF
"J.M"CRLF
"NE PASSEZ PAS"CRLF
"- DESCENDRE"CRLF
"DESC. AU PALIER"CRLF
"APERCU PP"CRLF
"INFO DSX"CRLF
"T\xc3\x89""L\xc3\x89""CHARGEMENT"CRLF
"TPR"CRLF
"AL TPR"CRLF
"SIGNE APPLIQUE"CRLF
"SIGNE"CRLF
"APPLIQUE"CRLF
"ELEV"CRLF
"EN13319"CRLF
"END"CRLF
"ALARME END"CRLF
"PRESS DE FIN "CRLF
"AL PRESS DE FIN"CRLF
"PRESS FIN"CRLF
"END/WOB/ICD"CRLF
"ALARMES END/WOB/CDI"CRLF
"ENTREE"CRLF
"PROF. EQUIVALENT NARCOTIQUE (END)"CRLF
"ERROR"CRLF
"ERREUR"CRLF
"ALTITUDE"CRLF
"ERREUR"CRLF
"A TO C"CRLF
"ERREUR"CRLF
"CALIBRATION"CRLF
"ERREUR"CRLF
"CHECKSUM"CRLF
"ERREUR"CRLF
"EEPROM"CRLF
"ERREUR"CRLF
"DERNIERE"CRLF
"PLONGEE"CRLF
"SORTIR DE L'ORIENTATION"CRLF
"EXIT TIME"CRLF
"EXTRA LARGE"CRLF
"ECHOUE"CRLF
"RAPID."CRLF
"FHE NE PEUT PAS"CRLF
"ETRE REGLEE A 0"CRLF
"QUAND FO2 < 0.21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"ECRAN RENVERSE"CRLF
"VOL"CRLF
"FO2"CRLF
"DOUCE"CRLF
"GAZ"CRLF
"GAZ 1"CRLF
"GAZ 2"CRLF
"GAZ 3"CRLF
"GAZ 4"CRLF
"CONSOM. DES GAZ"CRLF
"CHANGEMENT DE GAZ"CRLF
"AUTONOMI GAZ"CRLF
"TEMPS DE GAS RESTANT 5 MIN"CRLF
"PROF"CRLF
"PROFON. SM"CRLF
"GF"CRLF
"GF HAUT"CRLF
"GS (MAX)"CRLF
"GF BAS"CRLF
"GF/N2"CRLF
"GF UTILISES"CRLF
"GF"CRLF
"GF OU N2"CRLF
"ALLER A LA POSITION GPS?"CRLF
"REMONT"CRLF
"GPS"CRLF
"SUPPRIMER UNE POSITION GPS"CRLF
"MENU GPS"CRLF
"VOUS DEVEZ SUPPRIMER UNE "CRLF
"POSITION GPS POUR"CRLF
"SAUVEGARDER UNE NOUVELLE"CRLF
"PAS DE "CRLF
"SIGNAL GPS"CRLF
"RECHERCHE DE "CRLF
"SIGNAL GPS EN COURS"CRLF
"VERT"CRLF
"TGR"CRLF
"TGR POUR G & D"CRLF
"SUP"CRLF
"PPO2 ELEVEE"CRLF
"SP SUP"CRLF
"HISTORIQUE"CRLF
"PROF. MOYENNE"CRLF
"TEMP MIN"CRLF
"PROF. MAX."CRLF
"T-PLONGEE MAX"CRLF
"ALTITUDE MAX"CRLF
"HEURES PLONGEE"CRLF
"PRINCIPAL"CRLF
"MENU PRINCIPAL"CRLF
"H"CRLF
"H:MIN"CRLF
"CDI"CRLF
"ALARMES CDI"CRLF
"SI VOUS LE LIEZ A"CRLF
"IMPERIAL"CRLF
"- AUGMENTER"CRLF
"INFO"CRLF
"INITIALISATION"CRLF
"INITIALISATION DE GPS EN COURS"CRLF
"EST DEJA LIE A "CRLF
"EST REGLE A"CRLF
"CONTRE-DIFFUSION ISOBARIQUE"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"LANGUE"CRLF
"DERNIERE CALIBRATION"CRLF
"DERNIERE PLONGEE"CRLF
"DONNEES DE DERN."CRLF
"DERNIER GAZ"CRLF
"PROF. DERNIER PALIER"CRLF
"LIMITE"CRLF
"LIEA"CRLF
"TMT LIE"CRLF
"POSITION GPS SUPPRIMEE"CRLF
"LA POSITION GPS SAUVEGARDEE"CRLF
"CARNET"CRLF
"LIEN PERDU"CRLF
"TMT PERDU"CRLF
"PILE"CRLF
"BATTERIE FAIBLE"CRLF
"PPO2 TROP BAS"CRLF
"SP INF"CRLF
"TEMP MIN"CRLF
"M.J"CRLF
"M.J.A"CRLF
"MAGENTA"CRLF
"ECRAN PRINCIPAL"CRLF
"MENU PRINCIPAL"CRLF
"FABRICANT"CRLF
"MAX"CRLF
"PROF. MAX."CRLF
"PROF. MAX"CRLF
"PROF."CRLF
"MAX"CRLF
"T-PLONGEE MAX"CRLF
"ALTITUDE MAX"CRLF
"PPO2 MAX"CRLF
"MOYEN"CRLF
"METRIQUES"CRLF
"MIN"CRLF
"MIN:SEC"CRLF
"PALIER RATEE"CRLF
"MOD"CRLF
"MODE"CRLF
"MODELE"CRLF
"PLUS DE DONNEES"CRLF
"PLUS DE DONNEES"CRLF
"MES INFOS"CRLF
"UTILISER L'APPLICATION"CRLF
"DIVERLOG+ POUR"CRLF
"T\xc3\x89""L\xc3\x89""CHARGER VOTRE"CRLF
"FICHIER IMAGE DE INFO"CRLF
"N2"CRLF
"N2"CRLF
"ALARME N2 BAR"CRLF
"NOUVELLE"CRLF
"NOUVELLE/CONTINUE"CRLF
"SUIVANT"CRLF
"NITROGENE"CRLF
"NON"CRLF
"SANS PALIER"CRLF
"TEMPS SANS PALIER"CRLF
"PAS DE PLO."CRLF
"AUCUNE CELLULE O2 TROUVEE"CRLF
"VEUILLEZ CONNECTER UNE"CRLF
"CELLULE O2"CRLF
"PAS D'IMAGE"CRLF
"NON TMT"CRLF
"PAS DE"CRLF
"PLONGEE"CRLF
"DERNIERE"CRLF
"NON DISPONIBLE"CRLF
"NON DISPONIBLE"CRLF
"ANALYSEUR O2"CRLF
"O2 NARCOTIQUE"CRLF
"SAT. O2"CRLF
"SAT. O2 (FIN)"CRLF
"TEMPS O2"CRLF
"AJOUTER LE GAZ ANALYSE"CRLF
"A UNE LISTE?"CRLF
"AUCUNE CELLULE O2 TROUVEE "CRLF
"VEUILLEZ CONNECTER UNE"CRLF
"CELLULE O2"CRLF
"PRESSION SURFACE"CRLF
"PRET POUR"CRLF
"CALIBRATION"CRLF
"F\xc3\x9c""R OC-L UND OC-R"CRLF
"WIRD EINGESTELLT"CRLF
"25/45"CRLF
"BEST\xc3\x84""TIGEN?"CRLF
"CHOISIR LA LISTE DE GAZ "CRLF
"POUR ASSIGNER"CRLF
"CALIBRATION DE LA CELLULE O2"CRLF
"COMPLETEE"CRLF
" "CRLF
"VEUILLEZ CALIBRER LA CELLULE O2"CRLF
"AVANT L'ANALYSE"CRLF
" "CRLF
"LECTURE DU VOLTAGE DE LA"CRLF
"CELLULE O2"CRLF
" "CRLF
"OC"CRLF
"OC-1"CRLF
"OC-2"CRLF
"OC-3"CRLF
"OC-4"CRLF
"OC-5"CRLF
"OC-6"CRLF
"OC PPO2 DECO"CRLF
"OC-G"CRLF
"OC PPO2 MAX"CRLF
"OC PPO2 MIN"CRLF
"OC-D"CRLF
"OFF"CRLF
"ON"CRLF
"ORANGE"CRLF
"PAIRAGE"CRLF
"CODE"CRLF
"CALIBRATION EFFECTUEE"CRLF
"PERSONNELLES"CRLF
"PLAN"CRLF
"PPO2"CRLF
"PPO2 AL"CRLF
"PPO2 < 0.17 "CRLF
"CHANGEMENT IMPOSSIBLE"CRLF
"PPO2 (Max)"CRLF
"LIMITES PPO2"CRLF
"PRESS"CRLF
"PRESS A L'ACTIVATION"CRLF
"PRESSION"CRLF
"PRET"CRLF
"REFERENCE"CRLF
"REINIT. PROF. MOYENNE"CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"PARAMETRES SERONT"CRLF
"REINITIALES"CRLF
"(LES DON. DES PLONGE. SERONT CONSER.)"CRLF
"ETES-VOUS SUR?"CRLF
"REINIT. PARAMETRES"CRLF
"RESULTAT"CRLF
"TOURNEZ DANS"CRLF
"DE MULTIPLES"CRLF
"DIRECTIONS JUSQU'AU BIP"CRLF
"AL ITR"CRLF
"ITR ALARME"CRLF
"RUNTIME"CRLF
"SAC"CRLF
"PALIER DE SECUR"CRLF
"SALEE"CRLF
"SALT WATER"CRLF
"TAUX D'ECHANT"CRLF
"- SAUVEGARDER"CRLF
"OBTENIR LA POSITION GPS"CRLF
"ALLER A LA POSITION GPS?"CRLF
"SAUVEGARDE DU PROFIL"CRLF
"MER"CRLF
"SEARCH"CRLF
"RECHERCHE EN COURS"CRLF
"RE-CHERCHE DE TMT EN COURS"CRLF
"SEC"CRLF
"SEGMENTS"CRLF
"CHOISIR UN GAZ POUR ASSIGNER"CRLF
"NO DE SERIE"CRLF
"REG."CRLF
"REGLAGES ALARMES"CRLF
"SET BO GAS"CRLF
"REGLAGE FO2 DU GAZ DE "CRLF
"CALIBRATION"CRLF
"REGLAGE DECLIN."CRLF
"REGLAGES GAZ"CRLF
"REGLAGES GF"CRLF
"REG. GF HAUT"CRLF
"REGLAGES"CRLF
"REGLAGES SP"CRLF
"REGLAGES UTILITAIRES"CRLF
"REGLAGE"CRLF
"PARAMETRES"CRLF
"REINITIALES"CRLF
"REGLAGE"CRLF
"MENU REGLAGES"CRLF
"SIMULER LA PLONGEE"CRLF
"IMAGES"CRLF
"LENT"CRLF
"SM"CRLF
"NS:"CRLF
"SP"CRLF
"SP (SUP-INF)"CRLF
"CHANGEMENT DE SP"CRLF
"SPORT"CRLF
"STANDARD"CRLF
"INITIAL"CRLF
"TEMPS DEBUT"CRLF
"STOP"CRLF
"DUREE"CRLF
"SOMMAIRE"CRLF
"SURF-I"CRLF
"SURF-I"CRLF
"CHANGER BO\xcb\x83""CC"CRLF
"CHANGER CC\xcb\x83""BO"CRLF
"PRESS CHANGEM."CRLF
"PASSEZ A"CRLF
"PASSER A SP PERSONNEL"CRLF
"CHANGE A FO2"CRLF
"PASSER A SP SUPERIEUR"CRLF
"PASSER A SP INFERIEUR"CRLF
"SYSTEM ERROR"CRLF
"PRESS BOUT."CRLF
"PRESSION DE LA BOUTEILLE"CRLF
"CIBLE"CRLF
"POSITION CIBLE"CRLF
"TEC"CRLF
"TEMP"CRLF
"LE GAZ ACTUEL"CRLF
"PUIS ACTIVEZ"CRLF
"HEURE"CRLF
"FORMAT HEURE"CRLF
"LIMITES DE TEMPS"CRLF
"ALARME TTS"CRLF
"TEMPS AUTO-LUMI."CRLF
"SAT. TISSUS"CRLF
"TISSUS"CRLF
"COULEUR DES TITRES"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT G"CRLF
"TMT PILE FAIBLE"CRLF
"TMT NON DISPONIBLE"CRLF
"TMT D"CRLF
"N. SERIE"CRLF
"REGLER N. SERIE"CRLF
"STATUS TMT"CRLF
"CHANGEMENT TMT "CRLF
"A"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- CHANGER"CRLF
"- INVERSER"CRLF
"TOO DEEP"CRLF
"TROP RAPIDE"CRLF
"DECO TOTAL"CRLF
"PLONGEES TOTALES"CRLF
"T-PLONGEE TOTAL"CRLF
"RUNTIME TOTAL"CRLF
"REGLAGES TMT"CRLF
"TTS"CRLF
"PRESS. DE RET./FIN/CHANG."CRLF
"PRESS RET"CRLF
"AL PRESS DE RET."CRLF
"PRESS. DE RETOUR"CRLF
"PRESS DE RETOUR/FIN"CRLF
"AL PRESS DE RETOUR/FIN"CRLF
"TYPE"CRLF
"REGLE PENDANT"CRLF
"LA PLONGEE"CRLF
"UNITES"CRLF
"- REMONTER DANS"CRLF
"T.CHARGE  1"CRLF
"T.CHARGE  2"CRLF
"T.CHARGE  3"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"UTILITAIRES"CRLF
"VALEUR"CRLF
"VIBRATION"CRLF
"VIOLATION"CRLF
"ATTENDEZ LE BIP,"CRLF
"ATTENTION"CRLF
"ATTENTION! GAZ HYPOXIQUE"CRLF
"ALARME PILE FAIBLE"CRLF
"ATTENTION! PPO2 >1.60"CRLF
"TYPE D'EAU"CRLF
"ORIENTATION"CRLF
"ECRAN D'ACCUEIL"CRLF
"BLANC"CRLF
"SERA AUTOMATIQUEMENT"CRLF
"WOB"CRLF
"ALARME WOB"CRLF
"TRAVAIL RESPIRATOIRE"CRLF
"OUI"CRLF
"VOUS AVEZ ATTEINT VOTRE CIBLE"CRLF
};