#include"TxtStr_Order_DSX.h"
const char LangStr_Espanol[] = {
"3ra FILA IZQUIERDA"CRLF
"3ra FILA DERECHA"CRLF
"ACTUAL"CRLF
"PO2/PMO"CRLF
"AJUSTE"CRLF
"AIRE"CRLF
"ALARMA"CRLF
"ALARMA BATERIA BAJA"CRLF
"ALARMAS"CRLF
"ANALIZAR"CRLF
"ANALIZADOR"CRLF
"ANALIZANDO"CRLF
"ASC"CRLF
"ASC"CRLF
"ASCENSO DEMASIADO RAPIDO"CRLF
"SONIDO"CRLF
"ALARM ACUSTICA"CRLF
"SONIDO/VIBRACI\xc3\x93""N"CRLF
"AUTO"CRLF
"AUTO ILUM"CRLF
"AUTO ALTO"CRLF
"AUTO BAJO"CRLF
"CONSUMO MEDIO"CRLF
"PROF MEDIA"CRLF
"PROF MEDIA"CRLF
"TIEMPO INM MEDIO"CRLF
"AVG.SAC"CRLF
"TEMP MEDIA"CRLF
"CONSUMO DE GAS AUXILIAR"CRLF
"PLAN DE RESCATE"CRLF
"LIMITES DE PO2 AUXILIAR"CRLF
"BAR"CRLF
"BAT BIEN"CRLF
"BAT. BAJA"CRLF
"BATERIA"CRLF
"BATTERY TOO LOW"CRLF
"BLANCO"CRLF
"BLUETOOTH"CRLF
"DISP. BLUETOOTH"CRLF
"BLUETOOTH"CRLF
"EMPAREJAMIENTO"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"BRILLO"CRLF
"CALCULANDO"CRLF
"CALIBRAR"CRLF
"VOLVER A CALIBRAR"CRLF
"CALIBRADO EN BASE A"CRLF
"PUEDE SER DESACTIVADO"CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"CC-6 PRESION"CRLF
"CC-PRESION"CRLF
"CA"CRLF
"LIM SUP"CRLF
"TENSI\xc3\x93""N DE LA C\xc3\x89""LULA"CRLF
"CAMBIAR UBICACI\xc3\x93""N DE DESTINO"CRLF
"CHARGE"CRLF
"CRONO"CRLF
"LIMPIAR TEJIDOS"CRLF
"COMMUNICATION"CRLF
"COMPAS"CRLF
"COMPAS MENU"CRLF
"CONFIRMAR?"CRLF
"CONECTAR"CRLF
"CONECTADO"CRLF
"CONECTADO-BLUETOOTH"CRLF
"CONECTADO"CRLF
"CONSERVADURISMO"CRLF
"CONSERVADURISMO - SPORT"CRLF
"CONSERVADURISMO- TEC"CRLF
"CONSUMO"CRLF
"CONTINUO"CRLF
"CUENTA ATRAS"CRLF
"UBICACI\xc3\x93""N ACTUAL"CRLF
"PO2 ACTUAL"CRLF
"PRESION ACTUAL"CRLF
"SP PERS."CRLF
"CIAN"CRLF
"D/M/A"CRLF
"DATOS"CRLF
"DATOS 1"CRLF
"DATOS 2"CRLF
"DATOS 3"CRLF
"FECHA"CRLF
"FORMATO FECHA"CRLF
"FECHA & HORA"CRLF
"DC"CRLF
"INFO DC"CRLF
"ESTE"CRLF
"E"CRLF
"NORTH"CRLF
"N"CRLF
"SOUTH"CRLF
"S"CRLF
"WEST"CRLF
"W"CRLF
"DECO"CRLF
"DECO"CRLF
"ENTRADA DECO"CRLF
"DECO PO2"CRLF
"P. DECO"CRLF
"- REDUCIR"CRLF
"P. PROFUNDA"CRLF
"BORRAR UBICACI\xc3\x93""N?"CRLF
"LA PIZARRA"CRLF
"SE ELIMINAR\xc3\x81""."CRLF
"EST\xc3\x81 SEGURO?"CRLF
"ELIMINADA."CRLF
"PROF"CRLF
"PROF."CRLF
"AL PROF"CRLF
"ALARMA PROF"CRLF
"PROFUNDIDAD NARCOTICA EQUIVALENTE(END)"CRLF
"HYPOXIC TRESHOLD(HT)"CRLF
"PROFUNDIDAD MAXIMA OPERATIVA (MOD)"CRLF
"TRABAJO RESPIRATORIO (WOB)"CRLF
"LIMITES DE PROFUNDIDAD"CRLF
"DESAT"CRLF
"AJUSTE DISPOSITIVO"CRLF
"Dil PO2"CRLF
"ATENUADO A BRILLO"CRLF
"PANTALLA"CRLF
"AJUSTE PANTALLA"CRLF
"DISTANCIA"CRLF
"DATOS INM"CRLF
"MENU DE INMERSION"CRLF
"MODO DE INMERSION"CRLF
"PLAN DE INMERSION"CRLF
"ORGANIZADOR DE BUCEO"CRLF
"PERFIL GRAFICO DE INMERSION"CRLF
"AJUSTE DE INMERSION"CRLF
"TIEMPO DE DESCOMPRESI\xc3\x93""N "CRLF
"> 99 MIN"CRLF
"SIMULADOR DE BUCEO"CRLF
"TIEMPO INM"CRLF
"ALARMA TIEMPO INM"CRLF
"TIEMPO INM./TTS"CRLF
"ALARMAS TIEMPO INM./TTS"CRLF
"INMERSIONES"CRLF
"LIMITE SUPERIOR MAXIMO"CRLF
"SUPERA 400 FT"CRLF
"SUPERA 120 M"CRLF
"NO HAY SUFICIENTE TIEMPO"CRLF
"PARA DESCENSO"CRLF
"D.M"CRLF
"NO CAMBIAR"CRLF
"- ABAJO"CRLF
"!BAJAR! PARADA"CRLF
"VISTA PREVIA PP"CRLF
"INFO DSX"CRLF
"DTR"CRLF
"ALARMA DTR"CRLF
"PUNTO MARCADO"CRLF
"PUNTO"CRLF
"MARCADO"CRLF
"ELEV"CRLF
"EN13319"CRLF
"RES FINAL"CRLF
"ALARMA FINAL"CRLF
"RESERVA"CRLF
"AL GAS RESER."CRLF
"PRESION FINAL"CRLF
"END/WOB/ICD"CRLF
"END/WOB/ICD ALARMA"CRLF
"ENTRADA"CRLF
"PROF. NARCOTICA EQUIVALENTE"CRLF
"ERROR"CRLF
"ERROR"CRLF
"ALTITUDE"CRLF
"ERROR"CRLF
"A - D"CRLF
"ERROR"CRLF
"CALIBRADO"CRLF
"ERROR"CRLF
"CHECKSUM"CRLF
"ERROR"CRLF
"EEPROM"CRLF
"ERROR"CRLF
"ULT"CRLF
"INMERSION"CRLF
"SALIR DEL NAVEGADOR"CRLF
"TIEMPO DE SALIDA"CRLF
"EXTRA GRANDE"CRLF
"FALLO"CRLF
"RAPI."CRLF
"FHE NO PUEDE SER"CRLF
"FIJADO A 0"CRLF
"MIENTRAS FO2 < 21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"ROTAR PANTALLA"CRLF
"VUELO"CRLF
"FO2"CRLF
"DULCE"CRLF
"GAS"CRLF
"GAS 1"CRLF
"GAS 2"CRLF
"GAS 3"CRLF
"GAS 4"CRLF
"CONSUMOS DE GAS"CRLF
"CAMBIO GAS"CRLF
"TIEMPO GAZ"CRLF
"GAS TIEMPO RESTANTE 5 MIN"CRLF
"MEDIR"CRLF
"MEDIR ML"CRLF
"GF"CRLF
"GF MAX"CRLF
"GF (ALTO)"CRLF
"GF MIN"CRLF
"GF/TL"CRLF
"GF SELECCIONADO"CRLF
"GBFG"CRLF
"GBFG O N2 BAR"CRLF
"IR A LA UBICACI\xc3\x93""N?"CRLF
"ASCEND"CRLF
"GPS"CRLF
"BORRAR UBICACI\xc3\x93""N"CRLF
"MEN\xc3\x9a GPS"CRLF
"SE DEBE BORRAR UNA"CRLF
"UBICACI\xc3\x93""N PARA GUARDAR"CRLF
"UNA NUEVA UBICACI\xc3\x93""N"CRLF
"SE\xc3\x91""AL GPS NO"CRLF
"ENCONTRADA"CRLF
"ESPERANDO SE\xc3\x91""AL"CRLF
"GPS"CRLF
"VERDE"CRLF
"T.G.R"CRLF
"T.G.R. POR I & D"CRLF
"ALTO"CRLF
"PO2 ALTO"CRLF
"SP ALTO"CRLF
"HISTORIAL"CRLF
"PROF MEDIA"CRLF
"TEMP MIN"CRLF
"PROF M\xc3\x81""X"CRLF
"TIEMPO INM M\xc3\x81""X"CRLF
"ELEV. M\xc3\x81""X"CRLF
"TOTAL HORAS INM"CRLF
"INICIO"CRLF
"MENU INICIAL"CRLF
"H"CRLF
"H:MIN"CRLF
"ICD"CRLF
"ICD ALARMA"CRLF
"SI LO VINCULASTE CON"CRLF
"IMPERIAL"CRLF
"- AUMENTAR"CRLF
"INFO"CRLF
"INICIAR"CRLF
"INICIALIZANDO GPS"CRLF
"SE ENCUENTRA VINCULADO CON"CRLF
"EST\xc3\x81 AJUSTADO A"CRLF
"CONTRADIFUSION ISOBARICA"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"IDIOMA"CRLF
"ULT. VERSION"CRLF
"ULT-INM"CRLF
"DATOS ULT INM"CRLF
"ULT GAS"CRLF
"PROF. ULT. PARADA"CRLF
"LIMITE"CRLF
"CONECTADO"CRLF
"TMT CONECTADO "CRLF
"UBICACI\xc3\x93""N BORRADA"CRLF
"UBICACI\xc3\x93""N GUARDADA"CRLF
"REGISTRO"CRLF
"CONEXION PERDIDA"CRLF
"TMT PERDIDO"CRLF
"BATERIA"CRLF
"BATER\xc3\x8d""A BAJA"CRLF
"PO2 BAJO"CRLF
"SP BAJO"CRLF
"TEMP. BAJA"CRLF
"M.D"CRLF
"M/D/A"CRLF
"MAGENTA"CRLF
"PANTALLA PRINCIPAL"CRLF
"MENU PRINCIPAL"CRLF
"FABRICANTE"CRLF
"MAX"CRLF
"PROF M\xc3\x81""X"CRLF
"PROF M\xc3\x81""X"CRLF
"PROF"CRLF
"MAX"CRLF
"TIEMPO INM MAX"CRLF
"ALT. MAX"CRLF
"MAX PO2"CRLF
"MEDIO"CRLF
"METRICAS"CRLF
"MIN"CRLF
"MIN:SEG"CRLF
"DESCO FALLIDA"CRLF
"MOD"CRLF
"MODO"CRLF
"MODELO"CRLF
"MAS DATOS"CRLF
"MAS DATOS INM"CRLF
"MI INFO"CRLF
"UTILICE LA APP DIVERLOG+"CRLF
"PARA CARGAR EL ARCHIVO "CRLF
"DE IMAGEN DE "CRLF
"INFORMACI\xc3\x93""N"CRLF
"N2"CRLF
"N2 BAR"CRLF
"ALARMA N2 BAR"CRLF
"NUOVO"CRLF
"NUEVO O CONTINUO"CRLF
"SIGUIENTE"CRLF
"NITROGENO"CRLF
"NO"CRLF
"NO DECO"CRLF
"TIEMPO SIN DECO"CRLF
"NO BUCEAR"CRLF
"NO SE ENCUENTRA LA "CRLF
"C\xc3\x89""LULA DE O2"CRLF
"CONECTE LA C\xc3\x89""LULA DE O2"CRLF
"NO HAY TABLERO"CRLF
"NO TMT"CRLF
" "CRLF
"SIN BUCEAR AUN"CRLF
" "CRLF
"NO DISPONIBLE"CRLF
"NO DISP."CRLF
"ANALIZADOR DE O2"CRLF
"O2 NARCOTICO"CRLF
"SAT. O2"CRLF
"O2 SAT (FIN)"CRLF
"TIEMPO O2"CRLF
"A\xc3\x91""ADIR GAS ANALIZADO A"CRLF
"UNA LISTA DE GASES?"CRLF
"C\xc3\x89""LULA DE O2 AGOTADA"CRLF
"CONECTE UNA C\xc3\x89""LULA DE O2 "CRLF
"NUEVA"CRLF
"PRESI\xc3\x93""N DE SUPERFICIE"CRLF
"LISTO PARA "CRLF
"CALIBRAR"CRLF
"OC-L Y OC-R"CRLF
"SE AJUSTAR\xc3\x81""N A "CRLF
"25/45"CRLF
"CONTINUAR?"CRLF
"SELECCIONAR LISTA"CRLF
"GASES PARA ASIGNAR "CRLF
"CALIBRADO"CRLF
"DE LA C\xc3\x89""LULA DE"CRLF
"O2 COMPLETADO"CRLF
"CALIBRE LA C\xc3\x89""LULA"CRLF
"DE O2"CRLF
"ANTES DE ANALIZAR "CRLF
"LECTURA DE TENSI\xc3\x93""N DE LA"CRLF
"C\xc3\x89""LULA DE O2"CRLF
" "CRLF
"OC"CRLF
"OC-1"CRLF
"OC-2"CRLF
"OC-3"CRLF
"OC-4"CRLF
"OC-5"CRLF
"OC-6"CRLF
"OC DECO PO2"CRLF
"OC-I"CRLF
"OC MAX. PO2"CRLF
"OC MIN. PO2"CRLF
"OC-D"CRLF
"OFF"CRLF
"ON"CRLF
"NARANJA"CRLF
"EMPAREJAMIENTO"CRLF
"CONTRASE\xc3\x91""A"CRLF
"CALIBRADO CORRECTO"CRLF
"PERSONAL"CRLF
"PLAN"CRLF
"PO2"CRLF
"PO2 AL"CRLF
"PO2 < 0.17 NO SE "CRLF
"PUEDE CAMBIAR"CRLF
"PO2 (ALTO)"CRLF
"LIMITES PO2"CRLF
"PRESION"CRLF
"PRES EN ACTIV"CRLF
"PRESION"CRLF
"LISTO"CRLF
"REFERENCIA"CRLF
"REINICIAR PROFUNDIDAD MEDIA"CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"AJUSTES SER\xc3\x81""N"CRLF
"REINICIADOS"CRLF
"(SE CONSERVAR\xc3\x81""N LOS DATOS DE LAS INMERSIONES)"CRLF
"EST\xc3\x81""S SEGURO?"CRLF
"RESTABLECER AJUSTES"CRLF
"RESULTADO"CRLF
"GIRAR E INVERTIR EN VARIAS"CRLF
"DIRECCIONES HASTA"CRLF
"OIR PITIDO"CRLF
"AL INTERVALO"CRLF
"ALARMA INT"CRLF
"T. EJECUCI\xc3\x93""N"CRLF
"SAC"CRLF
"P. SEGURIDAD"CRLF
"SALADA"CRLF
"SALT WATER"CRLF
"FREC MUESTREO"CRLF
"- GUARDAR"CRLF
"GUARDAR LA UBICACI\xc3\x93""N ACTUAL"CRLF
"GUARDAR UBICACI\xc3\x93""N?"CRLF
"SAVING DIVE PROFILE"CRLF
"MAR"CRLF
"SEARCH"CRLF
"BUSCANDO"CRLF
"BUSCAR TMT"CRLF
"S"CRLF
"SEGMENTOS"CRLF
"SELECCIONAR GAS PARA ASIGNAR"CRLF
"SERIE"CRLF
"AJUSTE"CRLF
"AJUSTE ALARMAS"CRLF
"SET BO GAS"CRLF
"ESTABLECER FO2"CRLF
"DE GAS DE CALIBRADO"CRLF
"AJUSTE DECLINACION"CRLF
"AJUSTE DE GASES"CRLF
"ESTABLECER GF"CRLF
"ESTABLECER GF MAXIMO"CRLF
"MENU AJUSTES"CRLF
"AJUSTE DE SP"CRLF
"AJUSTE CONFIGURACION"CRLF
"AJUSTE"CRLF
"RESTABLECER"CRLF
"AJUSTES"CRLF
"AJUSTES"CRLF
"MENU AJUSTES"CRLF
"SIMULAR INMERSION"CRLF
"PIZARRA"CRLF
"LENT."CRLF
"SM"CRLF
"NS:"CRLF
"SP"CRLF
"SP (ALTO-BAJO)"CRLF
"CAMBIO DE SP"CRLF
"DEPORTIVO"CRLF
"ESTANDAR"CRLF
"INICIAR"CRLF
"HORA INICIO"CRLF
"ALTO"CRLF
"DETENER TIEMPO"CRLF
"RESUMEN"CRLF
"INT-SUPERF."CRLF
"INT-SUPERF."CRLF
"CAMBIAR BO\xcb\x83""CC"CRLF
"CAMBIAR CC\xcb\x83""BO"CRLF
"PRES. VUELTA"CRLF
"CAMBIAR TO"CRLF
"CAMBIAR A PERS."CRLF
"CAMBIAR A FO2"CRLF
"CAMBIO A SP ALTO"CRLF
"CAMBIO A SP BAJO"CRLF
"SYSTEM ERROR"CRLF
"PRES TANQUE"CRLF
"PRES TANQUE"CRLF
"DESTINO"CRLF
"UBICACI\xc3\x93""N DE DESTINO"CRLF
"TEC"CRLF
"TEMP"CRLF
"EL GAS ACTUAL NO"CRLF
"Y ACTIVAR"CRLF
"HORA"CRLF
"FORMATO HORA"CRLF
"LIMITE DE TIEMPO"CRLF
"ALARMA DE TIEMPO HASTA SUPERFICIE"CRLF
"BAJAR BRILLO EN"CRLF
"SATURACION DE TEJIDOS"CRLF
"TEJIDOS"CRLF
"COLOR DE TITULO"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT L"CRLF
"TMT BATERIA BAJA"CRLF
"TMT NO DISPONIBLE"CRLF
"TMT 6"CRLF
"N. DE SERIE"CRLF
"ESTABLECER \xe2\x84\x96 DE SERIE"CRLF
"ESTADO TMT"CRLF
"CAMBIAR TMT"CRLF
"A"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- CAMBIA GAS"CRLF
"- CAMBIAR"CRLF
"PROF EXCESIVA"CRLF
"VEL EXCESIVA"CRLF
"DESCO TOTAL"CRLF
"TOTAL INM"CRLF
"TIEMPO INM TOTAL"CRLF
"TIEMPO TOTAL"CRLF
"TRANSMISOR"CRLF
"TTS"CRLF
"PRES VUELTA/FIN/CAMBIO"CRLF
"GAS DE RET."CRLF
"ALARMA GAS RET."CRLF
"GAS DE RETORNO"CRLF
"REGRESAR/FINAL"CRLF
"REGRESAR/FINAL ALARMAS"CRLF
"TIPO"CRLF
"BAJO EL AGUA"CRLF
"  "CRLF
"UNIDADES"CRLF
"- ARRIBA"CRLF
"CARGADO 1"CRLF
"CARGADO 2"CRLF
"CARGADO 3"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"UTILIDADES"CRLF
"VALOR"CRLF
"VIBRACI\xc3\x93""N"CRLF
"TRANSGRESION"CRLF
"ESPERAR UN PITIDO"CRLF
"ADVERTENCIA"CRLF
"ADVERTENCIA! GAS HYPOXIC"CRLF
"AVISO BATERIA BAJA"CRLF
"ADVERTENCIA! PO2 >1.60"CRLF
"TIPO AGUA"CRLF
"NAVEGADOR"CRLF
"PANTALLA DE INICIO"CRLF
"BLANCO"CRLF
"SE AJUSTAR\xc3\x81""N A "CRLF
"WOB"CRLF
"ALARMA ESFUERZO"CRLF
"TRABAJO RESPIRATORIO "CRLF
"SI"CRLF
"HA LLEGADO AL DESTINO"CRLF
};