#include"TxtStr_Order_DSX.h"
const char LangStr_Polish[] = {
"3. RZ\xc4\x84""D Z LEWEJ"CRLF
"3. RZ\xc4\x84""D Z PRAWEJ"CRLF
"BIE\xc5\xbb\xc4\x84""CE"CRLF
"PO2/MOD"CRLF
"DOSTOSUJ"CRLF
"AIR"CRLF
"ALARMY"CRLF
"ALARM S\xc5\x81""ABA BAT."CRLF
"ALARMY"CRLF
"ANALIZA"CRLF
"ANALIZATOR"CRLF
"ANALIZA"CRLF
"RV"CRLF
"WYN"CRLF
"ZBYT SZYBKIE WYNURZANIE"CRLF
"S\xc5\x81""YSZALNY"CRLF
"ALARM D\xc5\xb9""W"CRLF
"D\xc5\xb9""WI\xc4\x98""K/WIBRACJA"CRLF
"AUTO"CRLF
"AUTO \xc5\x9a""CIEMNIANIE"CRLF
"AUTO WYSOKI"CRLF
"AUTO NISKI"CRLF
"\xc5\x9a""R. ZU\xc5\xbb""."CRLF
"\xc5\x9a""R. G\xc5\x81\xc4\x98""B."CRLF
"\xc5\x9a""RED. G\xc5\x81\xc4\x98""BOK."CRLF
"\xc5\x9a""RED. CZAS NURKOW"CRLF
"AVG.SAC"CRLF
"\xc5\x9a""RED. TEMP"CRLF
"ZU\xc5\xbb""YCIE BAILOUTU"CRLF
"BAILOUT PLAN"CRLF
"LIMITY PO2 BAILOUTU"CRLF
"BAR"CRLF
"BAT OK"CRLF
"S\xc5\x81""ABA BATERII"CRLF
"BATERI\xc4\x98"""CRLF
"BATTERY TOO LOW"CRLF
"PUSTO"CRLF
"BLUETOOTH"CRLF
"NAZWA BLUETOOTH"CRLF
"BLUETOOTH"CRLF
"PAROWANIE"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"JASNO\xc5\x9a\xc4\x86"""CRLF
"OBLICZANIE"CRLF
"KALIBRACJA"CRLF
"POWT\xc3\x93""RZ KALIBRACJ\xc4\x98"""CRLF
"KALIBROWANE W OPARCIU O"CRLF
"NIE MO\xc5\xbb""NA USTAWI\xc4\x86"""CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"P CC-6"CRLF
"CC- CI\xc5\x9a""NIENIE"CRLF
"ODLICZANIE"CRLF
"CEILING"CRLF
"NAPI\xc4\x98""CIE OGNIWA"CRLF
"ZMIE\xc5\x83 LOKALIZACJ\xc4\x98 DOCELOW\xc4\x84"""CRLF
"CHARGE"CRLF
"CHRONO"CRLF
"TKANKI CZYSTE"CRLF
"OCZEKIWANIE NA"CRLF
"KOMPAS"CRLF
"MENU KOMPASU"CRLF
"POTWIERDZI\xc4\x86""?"CRLF
"PO\xc5\x81\xc4\x84""CZENIE"CRLF
"PO\xc5\x81\xc4\x84""CZONO"CRLF
"PO\xc5\x81\xc4\x84""CZENIE-BLUETOOTH"CRLF
"PO\xc5\x81\xc4\x84""CZONO"CRLF
"KONSERWATYZM"CRLF
"KONSERWATYZM - SPORT"CRLF
"KONSERWATYZM- TEC"CRLF
"ZU\xc5\xbb""YCIE"CRLF
"CI\xc4\x84""G\xc5\x81""E"CRLF
"ODLICZANIE"CRLF
"AKTUALNA LOKALIZACJA"CRLF
"BIE\xc5\xbb\xc4\x84""CE PO2"CRLF
"CI\xc5\x9a""NIENIE BIE\xc5\xbb\xc4\x84""CE"CRLF
"W\xc5\x81""ASNY SP"CRLF
"CYJAN"CRLF
"D/M/R"CRLF
"DANE"CRLF
"DANE 1"CRLF
"DANE 2"CRLF
"DANE 3"CRLF
"DATA"CRLF
"FORMAT DATY"CRLF
"DATA I CZAS"CRLF
"KOMPUTERA"CRLF
"INFO KOMPUTERA"CRLF
"WSCH\xc3\x93""D"CRLF
"E"CRLF
"P\xc3\x93\xc5\x81""NOC"CRLF
"N"CRLF
"SOUTH"CRLF
"S"CRLF
"ZACH\xc3\x93""D"CRLF
"W"CRLF
"DEKO"CRLF
"DEKO"CRLF
"WEJ\xc5\x9a""CIE DEKO"CRLF
"DECO PO2"CRLF
"PRZYSTANKI DEKO"CRLF
"- ZMNIEJSZY\xc4\x86"""CRLF
"DEEP STOP"CRLF
"USU\xc5\x83 LOKALIZACJ\xc4\x98""?"CRLF
"OBRAZ"CRLF
"ZOSTANIE USUNI\xc4\x98""TA."CRLF
"NA PEWNO?"CRLF
"USUNI\xc4\x98""TA"CRLF
"G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86"""CRLF
"G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86"""CRLF
"AL. G\xc5\x81\xc4\x98""BOKO\xc5\x9a""CI"CRLF
"ALARM G\xc5\x81\xc4\x98""BOKO\xc5\x9a""CI"CRLF
"NARKOTYC. G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86 ODPOWIADA. (END)"CRLF
"PR\xc3\x93""G HIPOKSYCZNO\xc5\x9a""CI(HT)"CRLF
"MAKSYM. G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86 OPERACYJNA (MOD)"CRLF
"OPORY ODDECHOWE (WOB)"CRLF
"LIMITY G\xc5\x81\xc4\x98""BOKO\xc5\x9a""CI"CRLF
"DESATURACJA"CRLF
"USTAWIENIA URZ\xc4\x84""DZENIA"CRLF
"Dil PO2"CRLF
"\xc5\x9a""CIEMN. DO JASNO\xc5\x9a""CI"CRLF
"WY\xc5\x9a""WIETLACZ"CRLF
"USTAWIENIA WY\xc5\x9a""WIETLACZA"CRLF
"ODLEG\xc5\x81""O\xc5\x9a\xc4\x86"""CRLF
"DANE NURKOWANIA"CRLF
"MENU NURKOW"CRLF
"TRYB NURKOWANIA"CRLF
"PLAN NURKOWANIA"CRLF
"PLANNER NURKOWANIA"CRLF
"PROFIL NURKOWANIA"CRLF
"USTAWIENIA NURKOWANIA"CRLF
"CZAS DEKO"CRLF
"> 99 MIN"CRLF
"SYMULATOR NURKOWANIA"CRLF
"CZAS NURKOW"CRLF
"ALARM CZASU NURKOWANIA"CRLF
"CZASU NURKOWANIA/TTS"CRLF
"ALARMY CZASU NURKOWANIA/TTS"CRLF
"NURKOWANIA"CRLF
"MAKS. SUFIT DECO "CRLF
"PRZEKRACZA 400 FT"CRLF
"PRZEKRACZA 120M"CRLF
"ZA MA\xc5\x81""O CZASU"CRLF
"NA ZANURZENIE"CRLF
"D.M"CRLF
"NIE ZMIENIAJ"CRLF
"- W D\xc3\x93\xc5\x81 LISTY"CRLF
"ID\xc5\xb9 DO PRZYS."CRLF
"PODGL\xc4\x84""D DS"CRLF
"DSX INFO"CRLF
"DTR"CRLF
"AL DTR"CRLF
"ZASTOSOWANE ZNAKOWANIE"CRLF
"ZASTOSOWANE"CRLF
"ZNAKOWANIE"CRLF
"WYS."CRLF
"EN13319"CRLF
"KO\xc5\x83""COWE"CRLF
"ALARM KO\xc5\x83""C."CRLF
"CI\xc5\x9a""NIENIE KO\xc5\x83""COWE"CRLF
"AL CI\xc5\x9a""NIEN. KO\xc5\x83""C"CRLF
"CI\xc5\x9a""NIENIE KO\xc5\x83""COWE"CRLF
"END/WOB/ICD"CRLF
"ALARMY END/WOB/ICD"CRLF
"WPIS"CRLF
"NARKOTYCZNA G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86 ODPOWIADAJ\xc4\x84""CA"CRLF
"ERROR"CRLF
"B\xc5\x81\xc4\x84""D"CRLF
"ALTITUDE"CRLF
"B\xc5\x81\xc4\x84""D"CRLF
"OD A DO D"CRLF
"B\xc5\x81\xc4\x84""D"CRLF
"KALIBRACJI"CRLF
"B\xc5\x81\xc4\x84""D"CRLF
"SUMY KONTROLNEJ"CRLF
"B\xc5\x81\xc4\x84""D"CRLF
"EEPROM"CRLF
"B\xc5\x81\xc4\x84""D"CRLF
"W OSTATNIM"CRLF
"NURKOWANIU"CRLF
"WYJ\xc5\x9a""CIE Z NAWIGATORA"CRLF
"CZAS WYJ\xc5\x9a""CIA"CRLF
"BARDZO DU\xc5\xbb""Y"CRLF
"NIE POWIOD\xc5\x81""O SI\xc4\x98"""CRLF
"SZYB."CRLF
"FHE NIE MO\xc5\xbb""E BY\xc4\x86 "CRLF
"USTAWIONA NA 0"CRLF
"KIEDY F02<21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"OBR\xc3\x93""T EKRANU"CRLF
"NO FLY"CRLF
"FO2"CRLF
"S\xc5\x81""ODKA"CRLF
"GAZ"CRLF
"GAZ 1"CRLF
"GAZ 2"CRLF
"GAZ 3"CRLF
"GAZ 4"CRLF
"ZU\xc5\xbb""YCIE GAZ\xc3\x93""W"CRLF
"ZMIANA GAZU"CRLF
"CZAS GAZOWY"CRLF
"GAZU POZOSTA\xc5\x81""O NA 5 MIN"CRLF
"GAUGE"CRLF
"GAUGE SM"CRLF
"GF"CRLF
"GF WYSOKI "CRLF
"GF MAKS."CRLF
"GF NISKI"CRLF
"GF/N2"CRLF
"WYBRANY GF"CRLF
"GFBG"CRLF
"WYKRES GFBG LUB N2"CRLF
"UDA\xc4\x86 SI\xc4\x98 DO LOKALIZACJI?"CRLF
"DO G\xc3\x93""RY"CRLF
"GPS"CRLF
"USU\xc5\x83 LOKALIZACJ\xc4\x98"""CRLF
"MENU GPS"CRLF
"TRZEBA USUN\xc4\x84\xc4\x86 "CRLF
"LOKALIZACJ\xc4\x98"", ABY ZAPISA\xc4\x86 "CRLF
"NOW\xc4\x84 LOKALIZACJ\xc4\x98"""CRLF
"NIE ZNALEZIONO"CRLF
"SYGNA\xc5\x81""U GPS"CRLF
"OCZEKIWANIE NA"CRLF
"SYGNA\xc5\x81 GPS"CRLF
"ZIELONY"CRLF
"CPG"CRLF
"GTR DLA L & P"CRLF
"WYS."CRLF
"WYSOKIE PO2"CRLF
"WYSOKI SP"CRLF
"HISTORIA"CRLF
"\xc5\x9a""R. G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86"""CRLF
"TEMP. MINIMALNA"CRLF
"MAKS. G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86"""CRLF
"MAKS. CZAS NURKOW."CRLF
"WYS. MAKS."CRLF
"LICZBA GODZ. NURK."CRLF
"G\xc5\x81\xc3\x93""WNE"CRLF
"MENU G\xc5\x81\xc3\x93""WNE"CRLF
"GODZ"CRLF
"GODZ:MIN"CRLF
"ICD"CRLF
"ALARMY ICD"CRLF
"JE\xc5\x9a""LI PO\xc5\x81\xc4\x84""CZYSZ"CRLF
"IMPERIALNY"CRLF
"- ZWI\xc4\x98""KSZY\xc4\x86"""CRLF
"INFO"CRLF
"AKTYWUJ"CRLF
"GPS AKTYWUJ"CRLF
"JEST PO\xc5\x81\xc4\x84""CZONY Z"CRLF
"USTAWIONO NA "CRLF
"KONTRDYFUZJA IZOBARYCZNA"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"J\xc4\x98""ZYK"CRLF
"OSTATNIA KALIBRACJA"CRLF
"OST. NURK."CRLF
"DANE Z OST NURK"CRLF
"OSTATNI GAZ"CRLF
"OSTATNI PRZYSTANEK"CRLF
"LIMITY"CRLF
"PO\xc5\x81\xc4\x84""CZONO"CRLF
"PO\xc5\x81\xc4\x84""CZONO TMT"CRLF
"LOKALIZACJA USUNI\xc4\x98""TA"CRLF
"LOKALIZACJA ZAPISANA"CRLF
"LOG"CRLF
"UTRACONE PO\xc5\x81\xc4\x84""CZENIE"CRLF
"ZAGUBIONY PRZEKA\xc5\xb9""NIK"CRLF
"NISKI"CRLF
"BAT. BLISKA ROZ\xc5\x81""."CRLF
"NISKIE PO2"CRLF
"NISKI SP"CRLF
"MIN. TEMP"CRLF
"M.D"CRLF
"M.D.R"CRLF
"MAGENTA"CRLF
"WY\xc5\x9a""WIETLACZ G\xc5\x81\xc3\x93""WNY"CRLF
"MENU G\xc5\x81\xc3\x93""WNE"CRLF
"PRODUCENT"CRLF
"MAKS"CRLF
"MAKS. G\xc5\x81\xc4\x98""B."CRLF
"MAKS. G\xc5\x81\xc4\x98""B."CRLF
" "CRLF
"MAKS."CRLF
"MAKS. CZAS NURKOW"CRLF
"MAKS. WYS."CRLF
"MAKS. PO2"CRLF
"\xc5\x9a""RED."CRLF
"METRYCZNE"CRLF
"MIN"CRLF
"MIN:SEK"CRLF
"OMINI\xc4\x98""TA DEKO"CRLF
"MOD"CRLF
"TRYB"CRLF
"MODEL"CRLF
"WI\xc4\x98""CEJ DANYCH"CRLF
"WI\xc4\x98""CEJ DANYCH"CRLF
"MOJE INFO"CRLF
"U\xc5\xbb""YJ DZIENNIKA I APLIKACJI"CRLF
"DO PRZES\xc5\x81""ANIA PLIKU"CRLF
"Z OBRAZEM INFORMACJI"CRLF
" "CRLF
"N2"CRLF
"N2 BAR"CRLF
"AL N2 BAR"CRLF
"NOWE  CI\xc4\x84""G\xc5\x81""E"CRLF
"NOWE LUB CI\xc4\x84""G\xc5\x81""E"CRLF
"NAST\xc4\x98""PNY"CRLF
"AZOT"CRLF
"TAK"CRLF
"BEZ DEKO"CRLF
"CZAS BEZ DEKO"CRLF
"BRAK NURK."CRLF
"NIE ZNALEZIONO OGNIWA O2"CRLF
"POD\xc5\x81\xc4\x84""CZ"CRLF
"OGNIWO O2"CRLF
"BRAK OBRAZ\xc3\x93""W"CRLF
"BRAK TMT"CRLF
" "CRLF
"BRAK NURKOWA\xc5\x83"""CRLF
" "CRLF
"NIEDOSTEPNY"CRLF
"NIEDOSTEPNE"CRLF
"ANALIZATOR O2"CRLF
"NARKOTYCZNO\xc5\x9a\xc4\x86 O2"CRLF
"O2 SAT"CRLF
"SAT O2 (KO\xc5\x83""COWA)"CRLF
"CZAS O2"CRLF
"DODA\xc4\x86 ANALIZOWANY GAZ"CRLF
"DO LISTY GAZ\xc3\x93""W?"CRLF
"WYCZERPANE OGNIWO O2"CRLF
"POD\xc5\x81\xc4\x84""CZ NOWE"CRLF
"OGNIWO O2"CRLF
"CI\xc5\x9a""N. POWIERZ."CRLF
"GOT. DO"CRLF
"KALIBR."CRLF
"ZAR\xc3\x93""WNO OC-L JAK I OC-R"CRLF
"B\xc4\x98""D\xc4\x84 USTAWIONE NA"CRLF
"25/45"CRLF
"KONTYNUOWA\xc4\x86""?"CRLF
"WYBIERZ LIST\xc4\x98 GAZ\xc3\x93""W"CRLF
"DO PRZYPISANIA"CRLF
"KALIBRACJA"CRLF
"OGNIWA O2"CRLF
"ZAKO\xc5\x83""CZONA"CRLF
"SKALIBRUJ"CRLF
"OGNIWO O2"CRLF
"PRZED ANALIZ\xc4\x84 "CRLF
"ODCZYT NAPI\xc4\x98""CIA"CRLF
"OGNIWA O2"CRLF
" "CRLF
"OC"CRLF
"OC-1"CRLF
"OC-2"CRLF
"OC-3"CRLF
"OC-4"CRLF
"OC-5"CRLF
"OC-6"CRLF
"OC DEKO PO2"CRLF
"OC-L"CRLF
"OC MAKS. PO2"CRLF
"OC MIN. PO2"CRLF
"OC-R"CRLF
"WY\xc5\x81""."CRLF
"W\xc5\x81""."CRLF
"POMARA\xc5\x83""CZO."CRLF
"PAROWANIE"CRLF
"KOD DOST\xc4\x98""PU"CRLF
"KALIBRACJA POWIOD\xc5\x81""A SI\xc4\x98"""CRLF
"DANE OSOBOWE"CRLF
"PLAN"CRLF
"PO2"CRLF
"PO2 AL"CRLF
"PO2 < 0.17 NIE "CRLF
"MO\xc5\xbb""NA ZMIENI\xc4\x86"""CRLF
"PO2 (NAJWY\xc5\xbb""./MAKS)"CRLF
"LIMITY PO2"CRLF
"NACI\xc5\x9a""NIJ/CI\xc5\x9a""NIENIE"CRLF
"CI\xc5\x9a"". PODCZAS AKTYW."CRLF
"CI\xc5\x9a""NIENIE"CRLF
"GOTOWY"CRLF
"ODNIESIENIE"CRLF
"RESETUJ \xc5\x9a""REDNI\xc4\x84 G\xc5\x81\xc4\x98""BOKO\xc5\x9a\xc4\x86"""CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"USTAWIENIA ZOSTAN\xc4\x84 "CRLF
"ZRESETOWANE"CRLF
"(DANE DOT. NURKOWANIA B\xc4\x98""D\xc4\x84 ZACHOWANE)"CRLF
"CZY JESTE\xc5\x9a PEWIEN/PEWNA?"CRLF
"RESET USTAWIE\xc5\x83"""CRLF
"WYNIK"CRLF
"OBRACAJ I ODWRACAJ W R\xc3\x93\xc5\xbb""NYCH"CRLF
"KIERUNKACH A\xc5\xbb DO US\xc5\x81""YSZENIA"CRLF
"SYGNA\xc5\x81""U"CRLF
"PIC AL."CRLF
"PIC AL."CRLF
"RUNTIME"CRLF
"SAC"CRLF
"PRZYS. BEZP."CRLF
"S\xc5\x81""ONA"CRLF
"SALT WATER"CRLF
"PR\xc3\x93""BKOWANIE"CRLF
"- ZAPISZ"CRLF
"ZAPISZ BIE\xc5\xbb\xc4\x84""C\xc4\x84 LOKALIZACJ\xc4\x98"""CRLF
"ZAPISA\xc4\x86 LOKALIZACJ\xc4\x98""?"CRLF
"ZAPISYWANIE PROFILU"CRLF
"MORZE"CRLF
"SEARCH"CRLF
"SZUKANIE"CRLF
"SZUKAM PRZEK."CRLF
"SEK"CRLF
"SEGMENTY"CRLF
"WYBIERZ GAZ DO PRZYPISANIA"CRLF
"NR SER"CRLF
"USTAW"CRLF
"USTAW. ALARMU"CRLF
"SET BO GAS"CRLF
"USTAW KALIB."CRLF
"GAZ FO2"CRLF
"USTAW. DEKLINACJ\xc4\x98"""CRLF
"USTAW. GAZ"CRLF
"USTAW GF"CRLF
"USTAW GF WYSOKI"CRLF
"MENU USTAWIE\xc5\x83"""CRLF
"USTAW. SP"CRLF
"USTAW. NARZ\xc4\x98""DZI"CRLF
"USTAWIENIA"CRLF
"RESET"CRLF
"USTAWIE\xc5\x83"""CRLF
"USTAWIENIA"CRLF
"MENU USTAW."CRLF
"SYMULUJ NURKOWANIE"CRLF
"OBRACY"CRLF
"WOLN."CRLF
"SM"CRLF
"NS:"CRLF
"SP"CRLF
"SP (WYSOKI-NISKI)"CRLF
"ZMIANA SP"CRLF
"SPORT"CRLF
"STANDARD"CRLF
"POCZ\xc4\x84""TKOWE"CRLF
"CZAS ROZPOCZ\xc4\x98""CIA"CRLF
"STOP"CRLF
"CZAS"CRLF
"PODSUMOWANIE"CRLF
"PRZER. POW."CRLF
"PRZER. POW."CRLF
"ZMIE\xc5\x83 BO\xcb\x83""CC"CRLF
"ZMIE\xc5\x83 CC->BO"CRLF
"CI\xc5\x9a""N. PRZE\xc5\x81""."CRLF
"ZMIE\xc5\x83 NA"CRLF
"ZMIE\xc5\x83 NA W\xc5\x81""ASNY"CRLF
"ZMIE\xc5\x83 DO FO2"CRLF
"ZMIE\xc5\x83 NA WYSOKI"CRLF
"ZMIE\xc5\x83 NA NISKI"CRLF
"SYSTEM ERROR"CRLF
"P BUTLI"CRLF
"P BUTLI"CRLF
"CEL"CRLF
"LOKALIZACJA DOCELOWA"CRLF
"TEC"CRLF
"TEMP."CRLF
"GAZU RZECZYWISTEGO"CRLF
"NAST\xc4\x98""PNIE URUCHOM"CRLF
"CZAS"CRLF
"FORMAT CZASU"CRLF
"LIMITY CZASOWE"CRLF
"CZAS DO ALARMU POW."CRLF
"CZAS DO \xc5\x9a""CIEMN."CRLF
"NASYCENIE TKANEK"CRLF
"TKANKI"CRLF
"KOLOR LITER"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT L"CRLF
"S\xc5\x81""ABA BAT. PRZEK"CRLF
"PRZEK.  NIEDOSTEPNY"CRLF
"TMT 6"CRLF
"NR SER"CRLF
"USTAW NR SER"CRLF
"STATUS PRZEKA\xc5\xb9""NIKA"CRLF
"ZMIANA PRZEK."CRLF
"DO"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- TO SWITCH"CRLF
"- PRZEWIJANIE"CRLF
"ZA G\xc5\x81\xc4\x98""BOKO"CRLF
"ZA SZYBKO"CRLF
"CA\xc5\x81""KOWITE DEKO"CRLF
"LICZBA NURKOWA\xc5\x83"""CRLF
"CA\xc5\x81""K. CZAS NURKOW"CRLF
"CA\xc5\x81""KOWITY RUNTIME"CRLF
"PRZEKA\xc5\xb9""NIKI"CRLF
"TTS"CRLF
"C. ZAWR./C. ZAK./C. PRZE\xc5\x81""."CRLF
"CI\xc5\x9a"". POWROTU"CRLF
"AL CI\xc5\x9a""NIEN ZAWR"CRLF
"CI\xc5\x9a""NIENIE ZAWRACANIA"CRLF
"CI\xc5\x9a""NIENIE POWROTU/KO\xc5\x83""COWE"CRLF
"ALARM CI\xc5\x9a""NIENIA POWROTU/KO\xc5\x83""COWEGO"CRLF
"TYP"CRLF
"POD WOD\xc4\x84"""CRLF
"  "CRLF
"JEDNOSTKI"CRLF
"- W G\xc3\x93""R\xc4\x98 LISTY"CRLF
"WGRANO 1"CRLF
"WGRANO 2"CRLF
"WGRANO 3"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"NARZ\xc4\x98""DZIA"CRLF
"WARTO\xc5\x9a\xc4\x86"""CRLF
"WIBRACJA"CRLF
"NARUSZENIE"CRLF
"ZACZEKAJ NA SYGNA\xc5\x81"","CRLF
"OSTRZE\xc5\xbb""ENIE"CRLF
"UWAGA! GAZ HIPOKSYCZNY"CRLF
"OSTRZE\xc5\xbb""ENIE S\xc5\x81""ABA BAT."CRLF
"UWAGA! PO2 > 1.60"CRLF
"RODZAJ WODY"CRLF
"NAWIGATOR"CRLF
"EKRAN POWITALNY"CRLF
"BIA\xc5\x81""Y"CRLF
"B\xc4\x98""D\xc4\x84 USTAWIONE NA"CRLF
"WOB"CRLF
"ALARM WOB"CRLF
"OPORY ODDECHOWE"CRLF
"NIE"CRLF
"DOTAR\xc5\x81""E\xc5\x9a DO CELU"CRLF
};