/*CODE GENERATED PLEASE NOT MODIFY BY HAND!!!*/
#include"TxtStr_Order_DSX.h"
const char LangStr_EngLish[] = {
"3RD ROW LEFT"CRLF
"3RD ROW RIGHT"CRLF
"ACTUAL"CRLF
"PO2/MOD"CRLF
"ADJUST"CRLF
"AIR"CRLF
"ALARM"CRLF
"ALARM LOW BATT"CRLF
"ALARMS"CRLF
"ANALYZE"CRLF
"ANALYZER"CRLF
"ANALYZING"CRLF
"AR"CRLF
"ASC"CRLF
"ASCENT TOO FAST"CRLF
"AUDIBLE"CRLF
"AUDIBLE ALARM"CRLF
"AUDIBLE/VIBRATION"CRLF
"AUTO"CRLF
"AUTO DIM"CRLF
"AUTO HIGH"CRLF
"AUTO LOW"CRLF
"AVG.CONSUMP."CRLF
"AVG D"CRLF
"AVG DEPTH"CRLF
"AVG DIVE-T"CRLF
"AVG.SAC"CRLF
"AVG TEMP"CRLF
"BAILOUT GAS CONSUMP."CRLF
"BAILOUT PLAN"CRLF
"BAILOUT PO2 LIMITS"CRLF
"BAR"CRLF
"BATT GOOD"CRLF
"BATT LOW"CRLF
"BATTERY"CRLF
"BATTERY TOO LOW"CRLF
"BLANK"CRLF
"BLUETOOTH"CRLF
"BT DEVICE NAME"CRLF
"BLUETOOTH"CRLF
"PAIRING"CRLF
"BO"CRLF
"BO-1"CRLF
"BO-2"CRLF
"BO-3"CRLF
"BO-4"CRLF
"BO-5"CRLF
"BO-6"CRLF
"BO DECO PO2"CRLF
"BO GAS"CRLF
"BO MAX PO2"CRLF
"BO MIN PO2"CRLF
"BRIGHTNESS"CRLF
"CALCULATING"CRLF
"CALIBRATE"CRLF
"CALIBRATE AGAIN"CRLF
"CALIBRATED BASED ON"CRLF
"CANNOT BE SET"CRLF
"CC"CRLF
"CC-1"CRLF
"CC-2"CRLF
"CC-3"CRLF
"CC-4"CRLF
"CC-5"CRLF
"CC-6"CRLF
"CC-6 PRESS"CRLF
"CC-6 PRESSURE 400 PSI"CRLF
"CDT"CRLF
"CEILING"CRLF
"CELL VOLTAGE"CRLF
"CHANGE TARGET LOCATION"CRLF
"CHARGE"CRLF
"CHRONO"CRLF
"CLEAR TISSUES"CRLF
"COMMUNICATION"CRLF
"COMPASS"CRLF
"COMPASS MENU"CRLF
"CONFIRM?"CRLF
"CONNECT"CRLF
"CONNECTED"CRLF
"CONNECTED - BLUETOOTH"CRLF
"CONNECTION"CRLF
"CONSERVATISM"CRLF
"CONSERVATISM - SPORT"CRLF
"CONSERVATISM - TEC"CRLF
"CONSUMPTION"CRLF
"CONTINUOUS"CRLF
"COUNTDOWN"CRLF
"CURRENT LOCATION"CRLF
"CURRENT PO2"CRLF
"CURRENT PRESS"CRLF
"CUSTOM SP"CRLF
"CYAN"CRLF
"D/M/Y"CRLF
"DATA"CRLF
"DATA 1"CRLF
"DATA 2"CRLF
"DATA 3"CRLF
"DATE"CRLF
"DATE FORMAT"CRLF
"DATE & TIME"CRLF
"DC"CRLF
"DC INFO"CRLF
"EAST"CRLF
"E"CRLF
"NORTH"CRLF
"N"CRLF
"SOUTH"CRLF
"SOUTH"CRLF
"WEST"CRLF
"W"CRLF
"DECO"CRLF
"DECO"CRLF
"DECO ENTRY"CRLF
"DECO PO2"CRLF
"DECO STOPS"CRLF
"- DECREASE"CRLF
"DEEP STOPS"CRLF
"DELETE LOCATION?"CRLF
"SLATE"CRLF
"WILL BE DELETED."CRLF
"ARE YOU SURE?"CRLF
"DELETED."CRLF
"DEPTH"CRLF
"DEPTH"CRLF
"DEPTH AL"CRLF
"DEPTH ALARM"CRLF
"EQUIVALENT NARCOTIC DEPTH (END)"CRLF
"HYPOXIC TRESHOLD (HT)"CRLF
"MAXIMUM OPERATION DEPTH (MOD)"CRLF
"WORK OF BREATHING (WOB)"CRLF
"DEPTH LIMITS"CRLF
"DESAT"CRLF
"DEVICE SETTINGS"CRLF
"Dil PO2"CRLF
"DIM TO BRIGHTNESS"CRLF
"DISPLAY"CRLF
"DISPLAY SETTINGS"CRLF
"DISTANCE"CRLF
"DIVE DATA"CRLF
"DIVE MENU"CRLF
"DIVE MODE"CRLF
"DIVE PLAN"CRLF
"DIVE PLANNER"CRLF
"DIVE PROFILE GRAPH"CRLF
"DIVE SETTINGS"CRLF
"DECO TIME"CRLF
"> 99 MIN"CRLF
"DIVE SIMULATOR"CRLF
"DIVE TIME"CRLF
"DIVE TIME ALARM"CRLF
"DIVE TIME/TTS"CRLF
"DIVE TIME/TTS ALARMS"CRLF
"DIVES"CRLF
"MAXIMUM CEILING"CRLF
"EXCEEDS 420 FT"CRLF
"EXCEEDS 120M"CRLF
"NOT ENOUGH TIME"CRLF
"FOR THE DESCENT"CRLF
"D/M"CRLF
"DO NOT SWITCH"CRLF
"- DOWN LIST"CRLF
"DOWN TO STOP"CRLF
"DS PREVIEW"CRLF
"DSX INFO"CRLF
"DTR"CRLF
"DTR ALARM"CRLF
"EARMARK APPLIED"CRLF
"EARMARK"CRLF
"APPLIED"CRLF
"ELEV"CRLF
"EN13319"CRLF
"END"CRLF
"END ALARM"CRLF
"END PRESS"CRLF
"END PRESS AL"CRLF
"END PRESSURE"CRLF
"END/WOB/ICD"CRLF
"END/WOB/ICD ALARMS"CRLF
"ENTRY"CRLF
"EQUIVALENT NARCOTIC DEPTH"CRLF
"ERROR"CRLF
"ERROR"CRLF
"ALTITUDE"CRLF
"ERROR"CRLF
"A TO D"CRLF
"ERROR"CRLF
"CALIBRATION"CRLF
"ERROR"CRLF
"CHECKSUM"CRLF
"ERROR"CRLF
"EEPROM"CRLF
"ERROR"CRLF
"LAST DIVE"CRLF
"  "CRLF
"EXIT FROM WAYFINDER"CRLF
"EXIT TIME"CRLF
"EXTRA LARGE"CRLF
"FAILED"CRLF
"FAST"CRLF
"FHE CANNOT BE"CRLF
"SET TO 0"CRLF
"WHILE FO2 < 21"CRLF
"FiO2"CRLF
"FIRMWARE"CRLF
"FLIP SCREEN"CRLF
"FLY"CRLF
"FO2"CRLF
"FRESH"CRLF
"GAS"CRLF
"GAS 1"CRLF
"GAS 2"CRLF
"GAS 3"CRLF
"GAS 4"CRLF
"GAS CONSUMPTIONS"CRLF
"GAS SWITCH"CRLF
"GAS TIME"CRLF
"GAS TIME REMAINING 5 MIN"CRLF
"GAUGE"CRLF
"GAUGE SM"CRLF
"GF"CRLF
"GF HIGH"CRLF
"GF (HIGHEST)"CRLF
"GF LOW"CRLF
"GF/N2"CRLF
"GF SELECTED"CRLF
"GFBG"CRLF
"GFBG OR N2 BAR"CRLF
"GO TO LOCATION?"CRLF
"GO UP"CRLF
"GPS"CRLF
"DELETE LOCATION"CRLF
"GPS MENU"CRLF
"YOU HAVE TO DELETE"CRLF
"A LOCATION TO SAVE"CRLF
"A NEW LOCATION"CRLF
"GPS SIGNAL"CRLF
"NOT FOUND"CRLF
"WAITING FOR"CRLF
"GPS SIGNAL"CRLF
"GREEN"CRLF
"GTR"CRLF
"GTR FOR L&R"CRLF
"HIGH"CRLF
"HIGH PO2"CRLF
"HIGH SP"CRLF
"HISTORY"CRLF
"AV. DEPTH"CRLF
"LOWEST TEMP."CRLF
"MAX. DEPTH"CRLF
"MAX. DIVE TIME"CRLF
"MAX. ELEVATION"CRLF
"TOTAL DIVE HOURS"CRLF
"HOME"CRLF
"HOME MENU"CRLF
"HR"CRLF
"HR:MIN"CRLF
"ICD"CRLF
"ICD ALARM"CRLF
"IF YOU LINK IT TO"CRLF
"IMPERIAL"CRLF
"- INCREASE"CRLF
"INFO"CRLF
"INITIALIZE"CRLF
"INITIALIZING GPS"CRLF
"IS ALREADY LINKED TO"CRLF
"IS SET TO"CRLF
"ISOBARIC COUNTER DIFFUSION"CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe7\xae\x80\xe4\xbd\x93"""CRLF
"\xe4\xb8\xad\xe6\x96\x87\xe6\xad\xa3\xe9\xab\x94"""CRLF
"\xc4\x8c""E\xc5\xa0""TINA"CRLF
"ENGLISH"CRLF
"FRAN\xc3\x87""AIS"CRLF
"DEUTSCH"CRLF
"ITALIANO"CRLF
"\xed\x95\x9c\xea\xb5\xad\xec\x96\xb4"""CRLF
"POLSKI"CRLF
"PORTUGU\xc3\x8a""S"CRLF
"P\xd0\xa3""CC\xd0\x9a\xd0\x98\xd0\x99"""CRLF
"ESPA\xc3\x91""OL"CRLF
"LANGUAGE"CRLF
"LAST CALIBRATION"CRLF
"LAST DIVE"CRLF
"LAST DIVE DATA"CRLF
"LAST GAS"CRLF
"LAST STOP DEPTH"CRLF
"LIMIT"CRLF
"LINKED"CRLF
"LINKED TMT"CRLF
"LOCATION DELETED"CRLF
"LOCATION SAVED"CRLF
"LOG"CRLF
"LOST LINK"CRLF
"LOST TMT"CRLF
"LOW"CRLF
"LOW BATTERY"CRLF
"LOW PO2"CRLF
"LOW SP"CRLF
"LOW TEMP."CRLF
"M/D"CRLF
"M/D/Y"CRLF
"MAGENTA"CRLF
"MAIN DISPLAY"CRLF
"MAIN MENU"CRLF
"MANUFACTURER"CRLF
"MAX"CRLF
"MAX D"CRLF
"MAX DEPTH"CRLF
"MAX"CRLF
"DEPTH"CRLF
"MAX DIVE-T"CRLF
"MAX ELEV"CRLF
"MAX PO2"CRLF
"MEDIUM"CRLF
"METRIC"CRLF
"MIN"CRLF
"MIN:SEC"CRLF
"MISSED DECO"CRLF
"MOD"CRLF
"MODE"CRLF
"MODEL"CRLF
"MORE DATA"CRLF
"MORE DIVE DATA"CRLF
"MY INFO"CRLF
"USE DIVERLOG+ APP"CRLF
"TO UPLOAD YOUR"CRLF
"INFO IMAGE FILE"CRLF
" "CRLF
"N2"CRLF
"N2 BAR"CRLF
"N2 BAR ALARM"CRLF
"NEW"CRLF
"NEW OR CONTINUOUS"CRLF
"NEXT"CRLF
"NITROGEN"CRLF
"NO"CRLF
"NO DECO"CRLF
"NO DECO TIME"CRLF
"NO DIVE YET"CRLF
"NO O2 CELL FOUND"CRLF
"PLEASE CONNECT"CRLF
"O2 CELL"CRLF
"NO SLATES"CRLF
"NO TMT"CRLF
" "CRLF
"NO DIVE YET"CRLF
" "CRLF
"NOT AVAILABLE"CRLF
"NOT AVAIL"CRLF
"O2 ANALYZER"CRLF
"O2 NARCOTIC"CRLF
"O2 SAT"CRLF
"O2 SAT (END)"CRLF
"O2 TIME"CRLF
"ADD ANALYZED GAS"CRLF
"TO A GAS LIST?"CRLF
"O2 CELL DEPLETED"CRLF
"PLEASE CONNECT"CRLF
"A FRESH O2 CELL"CRLF
"SURFACE PRESSURE"CRLF
"READY FOR"CRLF
"CALIBRATION"CRLF
"BOTH OC-L AND OC-R"CRLF
"WILL BE SET TO "CRLF
"25/45"CRLF
"PROCEED?"CRLF
"SELECT GAS LIST"CRLF
"TO ASSIGN"CRLF
"O2 CELL"CRLF
"CALIBRATION"CRLF
"COMPLETE"CRLF
"PLEASE CALIBRATE"CRLF
"O2 CELL"CRLF
"BEFORE ANALYZING"CRLF
"READING"CRLF
"O2 CELL"CRLF
"VOLTAGE"CRLF
"OC"CRLF
"OC-1"CRLF
"OC-2"CRLF
"OC-3"CRLF
"OC-4"CRLF
"OC-5"CRLF
"OC-6"CRLF
"OC DECO PO2"CRLF
"OC-L"CRLF
"OC MAX. PO2"CRLF
"OC MIN. PO2"CRLF
"OC-R"CRLF
"OFF"CRLF
"ON"CRLF
"ORANGE"CRLF
"PAIRING"CRLF
"PASSCODE"CRLF
"PASSED CALIBRATION"CRLF
"PERSONAL"CRLF
"PLAN"CRLF
"PO2"CRLF
"PO2 AL"CRLF
"PO2 < 0.17"CRLF
"CANNOT SWITCH"CRLF
"PO2 (HIGHEST)"CRLF
"PO2 LIMITS"CRLF
"PRESS"CRLF
"PRESS AT ACTIVATION"CRLF
"PRESSURE"CRLF
"READY"CRLF
"REFERENCE"CRLF
"RESET AVERAGE DEPTH"CRLF
"AVERAGE DEPTH"CRLF
"WILL BE RESET"CRLF
"SETTINGS WILL"CRLF
"BE RESET TO DEFAULTS"CRLF
"(DIVE DATA WILL BE RETAINED)"CRLF
"ARE YOU SURE?"CRLF
"RESET SETTINGS"CRLF
"RESULT"CRLF
"ROTATE AND TURN OVER"CRLF
"IN MULTIPLE DIRECTIONS"CRLF
"UNTIL BEEP"CRLF
"RTI AL"CRLF
"RTI ALARM"CRLF
"RUNTIME"CRLF
"SAC"CRLF
"SAFETY STOP"CRLF
"SALT"CRLF
"SALT WATER"CRLF
"SAMPLE RATE"CRLF
"- SAVE"CRLF
"GET CURRENT LOCATION"CRLF
"SAVE LOCATION?"CRLF
"SAVING DIVE PROFILE"CRLF
"SEA"CRLF
"SEARCH"CRLF
"SEARCHING"CRLF
"SEARCHING FOR TMT"CRLF
"SEC"CRLF
"SEGMENTS"CRLF
"SELECT GAS TO ASSIGN"CRLF
"SERIAL NO."CRLF
"SET"CRLF
"SET ALARMS"CRLF
"SET BO GAS"CRLF
"SET CALIBRATION"CRLF
"GAS FO2"CRLF
"SET DECLIN"CRLF
"SET GASES"CRLF
"SET GF"CRLF
"SET GF HIGH"CRLF
"SET MENU"CRLF
"SET SP"CRLF
"SET UTILITIES"CRLF
"SETTING"CRLF
"SETTINGS"CRLF
"RESET"CRLF
"SETUP"CRLF
"SETUP MENU"CRLF
"SIMULATE DIVE"CRLF
"SLATES"CRLF
"SLOW"CRLF
"SM"CRLF
"SN:"CRLF
"SP"CRLF
"SP (HIGH-LOW)"CRLF
"SP SWITCH"CRLF
"SPORT"CRLF
"STANDARD"CRLF
"START"CRLF
"START TIME"CRLF
"STOP"CRLF
"STOP TIME"CRLF
"SUMMARY"CRLF
"SURFACE TIME"CRLF
"SURFACE TIME"CRLF
"SWITCH BO\xcb\x83""CC"CRLF
"SWITCH CC\xcb\x83""BO"CRLF
"SWITCH PRESS"CRLF
"SWITCH TO"CRLF
"SWITCH TO CUSTOM"CRLF
"SWITCH TO FO2"CRLF
"SWITCH TO HIGH"CRLF
"SWITCH TO LOW"CRLF
"SYSTEM ERROR"CRLF
"TANK PRESS"CRLF
"TANK PRESSURE"CRLF
"TARGET"CRLF
"TARGET LOCATION"CRLF
"TEC"CRLF
"TEMP"CRLF
"THE ACTUAL GAS"CRLF
"THEN ACTIVATE"CRLF
"TIME"CRLF
"TIME FORMAT"CRLF
"TIME LIMITS"CRLF
"TIME TO SURFACE ALARM"CRLF
"TIME TO DIM"CRLF
"TISSUE SATURATIONS"CRLF
"TISSUES"CRLF
"TITLES COLOR"CRLF
"TLBG"CRLF
"TMT"CRLF
"TMT 1"CRLF
"TMT 2"CRLF
"TMT 3"CRLF
"TMT 4"CRLF
"TMT 5"CRLF
"TMT 6"CRLF
"TMT L"CRLF
"TMT LOW BATT"CRLF
"TMT  NOT AVAILABLE"CRLF
"TMT R"CRLF
"SERIAL"CRLF
"SET SERIAL"CRLF
"TMT STATUS"CRLF
"TMT SWITCH"CRLF
"TO"CRLF
"TO ACTIVATE"CRLF
"TO ENTER YOUR"CRLF
"TO OPERATE"CRLF
"- TO SWITCH"CRLF
"- TOGGLE"CRLF
"TOO DEEP"CRLF
"TOO FAST"CRLF
"TOTAL DECO"CRLF
"TOTAL DIVES"CRLF
"TOTAL DIVE-T"CRLF
"TOTAL RUNTIME"CRLF
"TRANSMITTERS"CRLF
"TTS"CRLF
"TURN/END/SWITCH PRESS"CRLF
"TURN PRESS"CRLF
"TURN PRESS AL"CRLF
"TURN PRESSURE"CRLF
"TURN/END PRESS"CRLF
"TURN/END PRESS ALARMS"CRLF
"TYPE"CRLF
"UNDER WATER"CRLF
" "CRLF
"UNITS"CRLF
"- UP LIST"CRLF
"UPLOADED 1"CRLF
"UPLOADED 2"CRLF
"UPLOADED 3"CRLF
"USB"CRLF
"USE PC PROGRAM"CRLF
"UTILITIES"CRLF
"VALUE"CRLF
"VIBRATION"CRLF
"VIOLATION"CRLF
"WAIT FOR BEEP, "CRLF
"WARNING"CRLF
"WARNING! HYPOXIC GAS."CRLF
"WARNING LOW BATT"CRLF
"WARNING! PO2 > 1.60"CRLF
"WATER TYPE"CRLF
"WAYFINDER"CRLF
"WELCOME SCREEN"CRLF
"WHITE"CRLF
"WILL BE SET TO"CRLF
"WOB"CRLF
"WOB ALARM"CRLF
"WORK OF BREATHING"CRLF
"YES"CRLF
"YOU REACHED TO YOUR TARGET"CRLF
};